/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaire;

import Classe.ClasseCaisse;
import Classe.ClasseDepense;
import Gestion.GestCaisse;
import Gestion.GestClient;
import Gestion.GestDepense;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELLINA
 */
public class FormDepense extends javax.swing.JPanel {

    /**
     * Creates new form FormDepense
     */
    public FormDepense() {
        initComponents();
        ChargeTable();
        AffCaisse();
        labdateAct.setText(dateActuel());
        tfcaisse.setVisible(false);
        tfnum.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labnum = new javax.swing.JLabel();
        tfnum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfcaisse = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfcaisse1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labdateAct = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        tfmontant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfmotif = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labmotif = new javax.swing.JLabel();
        labmontant = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfmois = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        btnajout1 = new javax.swing.JButton();
        btnmodif = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        btnannul = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledep = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfrecherche = new javax.swing.JTextField();

        labnum.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labnum.setForeground(new java.awt.Color(255, 0, 0));

        tfnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfnumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnumKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel3.setText("N° Dépense:");

        tfcaisse.setEditable(false);
        tfcaisse.setBackground(new java.awt.Color(255, 255, 255));
        tfcaisse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcaisse.setText("0");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DEPENSE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(433, 433, 433))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "caisse", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel16.setText("Solde final");

        tfcaisse1.setEditable(false);
        tfcaisse1.setBackground(new java.awt.Color(255, 255, 255));
        tfcaisse1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfcaisse1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcaisse1.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel11.setText("Ariary");

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel12.setText("Date actuelle");

        labdateAct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labdateAct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(62, 62, 62))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfcaisse1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(labdateAct, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(labdateAct, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcaisse1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(23, 23, 23))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel4.setText("Date:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 6, 64, 30));

        tfdate.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(tfdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 6, 185, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel5.setText("Montant:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        tfmontant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfmontantKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfmontantKeyTyped(evt);
            }
        });
        jPanel4.add(tfmontant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel6.setText("Motif:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 30));

        tfmotif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfmotifKeyTyped(evt);
            }
        });
        jPanel4.add(tfmotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ariary");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        labmotif.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labmotif.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(labmotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 100, 110, 30));

        labmontant.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labmontant.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(labmontant, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 90, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel8.setText("Mois de dépense:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        tfmois.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01(Jan)", "02(Fév)", "03(Mar)", "04(Avr)", "05(Mai)", "06(Juin)", "07(Juil)", "08(Aôut)", "09(Sépt)", "10(Oct)", "11(Nov)", "12(Déc)" }));
        jPanel4.add(tfmois, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 50, 180, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnajout1.setBackground(new java.awt.Color(255, 255, 255));
        btnajout1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnajout1.setForeground(new java.awt.Color(0, 51, 255));
        btnajout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajout.jpg"))); // NOI18N
        btnajout1.setText("Ajouter");
        btnajout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajout1ActionPerformed(evt);
            }
        });

        btnmodif.setBackground(new java.awt.Color(255, 255, 255));
        btnmodif.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnmodif.setForeground(new java.awt.Color(0, 51, 255));
        btnmodif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modif2.jpg"))); // NOI18N
        btnmodif.setText("Modifier");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        btnsuppr.setBackground(new java.awt.Color(255, 255, 255));
        btnsuppr.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnsuppr.setForeground(new java.awt.Color(0, 51, 255));
        btnsuppr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppr1.jpg"))); // NOI18N
        btnsuppr.setText("Supprimer");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });

        btnannul.setBackground(new java.awt.Color(255, 255, 255));
        btnannul.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnannul.setForeground(new java.awt.Color(0, 51, 255));
        btnannul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/annuler1.jpg"))); // NOI18N
        btnannul.setText("Annuler");
        btnannul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmodif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnajout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnannul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnajout1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmodif)
                .addGap(18, 18, 18)
                .addComponent(btnsuppr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnannul)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        tabledep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledep);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        tfrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfrechercheKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfrecherche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     private String dateActuel(){
        Date daty=new Date();
        String dat=DateFormat.getDateInstance().format(daty);
        return dat;
    }
    private void btnajout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajout1ActionPerformed
        // TODO add your handling code here:
        Ajouter();
        ChargeTable();
        Annuler();
    }//GEN-LAST:event_btnajout1ActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        // TODO add your handling code here:
        Modifier();
        ChargeTable();
        Annuler();
    }//GEN-LAST:event_btnmodifActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
        // TODO add your handling code here:
        Supprimer();
        ChargeTable();
        Annuler();
    }//GEN-LAST:event_btnsupprActionPerformed

    private void btnannulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulActionPerformed
        // TODO add your handling code here:
        Annuler();
    }//GEN-LAST:event_btnannulActionPerformed

    private void tabledepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledepMouseClicked
        i=tabledep.getSelectedRow();
        Deplacer(i);
    }//GEN-LAST:event_tabledepMouseClicked

    private void tfnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnumKeyReleased
        // TODO add your handling code here:
        AffCaisse();
    }//GEN-LAST:event_tfnumKeyReleased

    private void tfmontantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmontantKeyReleased
        // TODO add your handling code here:
        AffCaisse();
    }//GEN-LAST:event_tfmontantKeyReleased

    private void tfnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnumKeyTyped
        // TODO add your handling code here:
        labnum.setText("Caractère invalide");
        String valeur = tfnum.getText().toString();
        int ln = valeur.length();
        if (tfnum.getText().matches("[0-9]*")) {
            tfnum.setText(valeur);
            labnum.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfnum.setText(valeur);
            labnum.setVisible(true);
            int val = 0;
        }
        
    }//GEN-LAST:event_tfnumKeyTyped

    private void tfmotifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmotifKeyTyped
        // TODO add your handling code here:
                labmotif.setText("Caractère invalide");
        String valeur = tfmotif.getText().toString();
        int ln = valeur.length();
        if (tfmotif.getText().matches("[A-Z,a-z,0-9,é,à,è,ù,ç,',â,+,/,-,*, ]*")) {
            tfmotif.setText(valeur);
            labmotif.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfmotif.setText(valeur);
            labmotif.setVisible(true);
            int val = 0;
        }
        
    }//GEN-LAST:event_tfmotifKeyTyped

    private void tfmontantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmontantKeyTyped
        // TODO add your handling code here:
           labmontant.setText("Caractére invalide");
        String valeur = tfmontant.getText().toString();
        int ln = valeur.length();
        if (tfmontant.getText().matches("[0-9]*")) {
            tfmontant.setText(valeur);
            labmontant.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfmontant.setText(valeur);
            labmontant.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfmontantKeyTyped

    private void tfrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfrechercheKeyReleased
        // TODO add your handling code here:
        Recherche1();
    }//GEN-LAST:event_tfrechercheKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajout1;
    private javax.swing.JButton btnannul;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labdateAct;
    private javax.swing.JLabel labmontant;
    private javax.swing.JLabel labmotif;
    private javax.swing.JLabel labnum;
    private javax.swing.JTable tabledep;
    private javax.swing.JTextField tfcaisse;
    private javax.swing.JTextField tfcaisse1;
    private com.toedter.calendar.JDateChooser tfdate;
    private javax.swing.JComboBox tfmois;
    private javax.swing.JTextField tfmontant;
    private javax.swing.JTextField tfmotif;
    private javax.swing.JTextField tfnum;
    private javax.swing.JTextField tfrecherche;
    // End of variables declaration//GEN-END:variables
    private int i;
    private Connection con;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    
    
     private void Ajouter(){
         String num = tfnum.getText();
         String datedep= ((JTextField)tfdate.getDateEditor().getUiComponent()).getText();
         String mon = tfmontant.getText();
         String mot = tfmotif.getText();
         String moisdep = tfmois.getSelectedItem().toString();
       
        ClasseDepense cl = new ClasseDepense(num, datedep, mon, mot, moisdep) ;
        if ((datedep.equals("")||mon.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
                GestDepense gd= new  GestDepense();
                gd.insert(cl) ;
                Caisse();
                SommeTotal();
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
    }
     
    
    
    private void AffichersurTable(){
        
    String num = tfnum.getText();
    String datedep= ((JTextField)tfdate.getDateEditor().getUiComponent()).getText();
    String mon = tfmontant.getText();
    String mot = tfmotif.getText();
    String moisdep = tfmois.getSelectedItem().toString();
       
    try {
	    dt.setRowCount(0);//vider la list 
            GestDepense gd = new  GestDepense();
	    Rs = gd.getAll();
	    while(Rs.next()){
                num = Rs.getString("num_dep");
                datedep = Rs.getString("date_dep");
                mon = Rs.getString("montant_dep");
                mot = Rs.getString("motif_dep");
                moisdep = Rs.getString("mois_dep");

                 Object[] dep = {num,datedep,mon,mot,moisdep} ;
	        dt.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    }
    
     
    private void ChargeTable(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt = new DefaultTableModel();
            dt.addColumn("ID");
            dt.addColumn("Date dépense");
            dt.addColumn("Montant de dépense");
            dt.addColumn("Motif de dépense");
            dt.addColumn("Mois de dépense");
            
            
                   
            tabledep.setModel(dt);
	    AffichersurTable();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
    
     private void Modifier(){
       String num = tfnum.getText();
       String datedep= ((JTextField)tfdate.getDateEditor().getUiComponent()).getText();
       String mon = tfmontant.getText();
       String mot = tfmotif.getText();
       String moisdep = tfmois.getSelectedItem().toString();
       
        ClasseDepense cl = new ClasseDepense(num, datedep, mon, mot, moisdep) ;
        if (num.equals("")||(datedep.equals("")||mon.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez cliquer sur le tableau de dépense)");
        }else{
            try{
            if(JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment modifier cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
                
                    GestDepense ge = new GestDepense() ;
                    ge.update(cl.getIdDep(),cl) ;
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erreur de modification \n"+e); 
            }
        }
   }
     
   private void Supprimer(){
       String num = tfnum.getText();
       String datedep= ((JTextField)tfdate.getDateEditor().getUiComponent()).getText();
       String mon = tfmontant.getText();
       String mot = tfmotif.getText();
       String moisdep = tfmois.getSelectedItem().toString();
       
        ClasseDepense cl = new ClasseDepense(num, datedep, mon, mot, moisdep) ;
        if (mot.equals("")||num.equals("")||(datedep.equals("")||mon.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez cliquer sur le tableau de dépense");
        }else{
            try{
                if(JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
                  
                    GestClient ge = new GestClient();
                    ge.delete(cl.getIdDep());
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erreur de suppression"+e); 
            }
        }
   }
   
   private void Annuler(){
        tfnum.setText("");
        tfdate.setCalendar(null);
        tfmontant.setText("");
        tfmotif.setText("");
        
        }

    private void Deplacer(int i) {
        try {
            //((JTextField)date.getDateEditor().getUiComponent()).setText(tabrec.getValueAt(i,0).toString());
            tfnum.setText(tabledep.getValueAt(i, 0).toString());
            ((JTextField)tfdate.getDateEditor().getUiComponent()).setText(tabledep.getValueAt(i, 1).toString());
            tfmontant.setText(tabledep.getValueAt(i, 2).toString());
            tfmotif.setText(tabledep.getValueAt(i, 3).toString());
            tfmois.setSelectedItem(tabledep.getValueAt(i,4).toString());
        }
        catch (Exception e) {
        }
        
    }
    
    private void Caisse(){
         String num = tfnum.getText();
         String datedep= ((JTextField)tfdate.getDateEditor().getUiComponent()).getText();
         String mon = tfmontant.getText();
         String caisse = tfcaisse.getText();
         String caisse1 = tfcaisse1.getText();
         String mot = tfmotif.getText();
         String moisdep = tfmois.getSelectedItem().toString();
         
        ClasseCaisse cl = new ClasseCaisse(caisse);
        ClasseDepense cl2 = new ClasseDepense(num, datedep, mon, mot, moisdep) ;
        if ((datedep.equals("")||mon.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
                GestCaisse gd= new  GestCaisse();
                //gd.insert1(cl) ;
                gd.update1( cl, cl2.getMontantDep());
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
    
    }
    
    public void AffCaisse(){
        try{    				
               Class.forName("com.mysql.jdbc.Driver");
                con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
                 St = con.createStatement();
               Rs=St.executeQuery("select sum(solde_caisse) from caisse");    
               

              while (Rs.next()) {
                   tfcaisse.setText(Rs.getString("sum(solde_caisse)"));
                   tfcaisse1.setText(Rs.getString("sum(solde_caisse)"));
            }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
    }
    
    public void SommeTotal(){          
            String a = tfmontant.getText();
            Integer a1=new Integer(a);
            int dep = a1.intValue();
            
            String b = tfcaisse.getText();
            Integer b1=new Integer(b);
            int caiss = b1.intValue();
            
            int tot = (int) (caiss - dep);
            String stot = new String();
            stot =String.valueOf(tot);
            tfcaisse1.setText(stot);
             //tfcaisse.setText(stot);
            
     }
    
    private void Recherche1() {                                           
        String rech=tfrecherche.getText();
        String num = tfnum.getText();
        String datedep= ((JTextField)tfdate.getDateEditor().getUiComponent()).getText();
        String mon = tfmontant.getText();
        String mot = tfmotif.getText();
        String moisdep = tfmois.getSelectedItem().toString();
        try{
            dt.setRowCount(0);
            Rs=St.executeQuery("SELECT * FROM depense WHERE (num_dep LIKE '%"+rech+"%' OR date_dep LIKE '%"+rech+"%' OR montant_dep LIKE '%"+rech+"%'  OR mois_dep LIKE '%"+rech+"%' OR motif_dep LIKE '%"+rech+"%')");
            i=0;
            while(Rs.next()){
                num = Rs.getString("num_dep");
                datedep = Rs.getString("date_dep");
                mon = Rs.getString("montant_dep");
                mot = Rs.getString("motif_dep");
                moisdep = Rs.getString("mois_dep");

                 Object[] dep = {num,datedep,mon,mot,moisdep} ;
	        dt.addRow(dep);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }
    
}
   
     



