/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaire;

import Classe.ClasseCaisse;
import Classe.ClasseCommander;
import Classe.ClassePaiement;
import Gestion.GestCaisse;
import Gestion.GestCommande;
import Gestion.GestPaiement;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELLINA
 */
public class FormPaiement extends javax.swing.JPanel {

    /**
     * Creates new form FormPaiement
     */
    public FormPaiement() {
        initComponents();
        ChargeTable();
        ChargerCombo();
        labdateAct.setText(dateActuel());
        AffCaisse();
        tfcaisse.setVisible(false);
        tfnumpaiem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfcaisse = new javax.swing.JTextField();
        tfnumpaiem = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbnumcom = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tfnomcli = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        tfnomact = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        tftypeact = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        tfprencli = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        tfdureact = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        tfmontant = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        datepaiem = new com.toedter.calendar.JDateChooser();
        jPanel13 = new javax.swing.JPanel();
        tfdateact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbmode = new javax.swing.JComboBox();
        tfmois = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnajout = new javax.swing.JButton();
        btnmodif = new javax.swing.JButton();
        btnannul = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablepaiem = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfcaisse1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labdateAct = new javax.swing.JLabel();
        tfrecherche = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        tfcaisse.setEditable(false);
        tfcaisse.setBackground(new java.awt.Color(255, 255, 255));
        tfcaisse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcaisse.setText("0");

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel7.setText("Numéro paiement:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAIEMENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel8.setText("Numéro commande:");

        cbnumcom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choisir un numéro" }));
        cbnumcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnumcomActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel2.setText("Nom client:");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel3.setText("Prénom client:");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel4.setText("Nom de l'activité:");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel5.setText("Type activité:");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel9.setText("Durée activité:");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tfnomcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnomcliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfnomcli)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfnomcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfnomact)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfnomact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tftypeact)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tftypeact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfprencli)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfprencli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfdureact)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfdureact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbnumcom, 0, 200, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbnumcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel6.setText("Date de paiement:");

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel13.setText("Mode de paiement:");

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel14.setText("Montant à payer:");

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfmontant, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tfmontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel15.setText("Ariary");

        datepaiem.setBackground(new java.awt.Color(255, 255, 255));
        datepaiem.setDateFormatString("yyyy-MM-dd");

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tfdateact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdateactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfdateact)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfdateact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel10.setText("Date commande:");

        cbmode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En espèce", "Par chèque bancaire" }));
        cbmode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmodeActionPerformed(evt);
            }
        });

        tfmois.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01(Jan)", "02(Fév)", "03(Mar)", "04(Avr)", "05(Mai)", "06(Juin)", "07(Juil)", "08(Aôut)", "09(Sépt)", "10(Oct)", "11(Nov)", "12(Déc)" }));

        jLabel18.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel18.setText("Mois du paiement:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfmois, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(datepaiem, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbmode, javax.swing.GroupLayout.Alignment.LEADING, 0, 182, Short.MAX_VALUE)
                                .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datepaiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        btnajout.setBackground(new java.awt.Color(255, 255, 255));
        btnajout.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnajout.setForeground(new java.awt.Color(0, 51, 255));
        btnajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajout.jpg"))); // NOI18N
        btnajout.setText("Ajouter");
        btnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutActionPerformed(evt);
            }
        });

        btnmodif.setBackground(new java.awt.Color(255, 255, 255));
        btnmodif.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnmodif.setForeground(new java.awt.Color(0, 51, 255));
        btnmodif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modif2.jpg"))); // NOI18N
        btnmodif.setText("Modifier");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        btnannul.setBackground(new java.awt.Color(255, 255, 255));
        btnannul.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnannul.setForeground(new java.awt.Color(0, 51, 255));
        btnannul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/annuler1.jpg"))); // NOI18N
        btnannul.setText("Annuler");
        btnannul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulActionPerformed(evt);
            }
        });

        btnsuppr.setBackground(new java.awt.Color(255, 255, 255));
        btnsuppr.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnsuppr.setForeground(new java.awt.Color(0, 51, 255));
        btnsuppr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppr1.jpg"))); // NOI18N
        btnsuppr.setText("Supprimer");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Facture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnajout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnsuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnannul, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnannul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        tablepaiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablepaiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepaiemMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablepaiem);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caisse", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Cambria", 1, 12))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel16.setText("Solde final dans la caisse");

        tfcaisse1.setEditable(false);
        tfcaisse1.setBackground(new java.awt.Color(255, 255, 255));
        tfcaisse1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfcaisse1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcaisse1.setText("0");

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        jLabel11.setText("Ariary");

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel12.setText("Date actuelle");

        labdateAct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfcaisse1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labdateAct, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labdateAct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11))
                    .addComponent(tfcaisse1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        tfrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrechercheActionPerformed(evt);
            }
        });
        tfrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfrechercheKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
     private String dateActuel(){
        Date daty=new Date();
        String dat=DateFormat.getDateInstance().format(daty);
        return dat;
    }
    private void btnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutActionPerformed
        // TODO add your handling code here:
        Ajouter();
        ChargeTable();
        Annuler();
        //ChargerCombo();
    }//GEN-LAST:event_btnajoutActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        // TODO add your handling code here:
        Modifier();
        ChargeTable();
        Annuler();
        //ChargerCombo();
    }//GEN-LAST:event_btnmodifActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
        // TODO add your handling code here:
        Supprimer();
        ChargeTable();
        Annuler();
        //ChargerCombo();
    }//GEN-LAST:event_btnsupprActionPerformed

    private void btnannulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulActionPerformed
        // TODO add your handling code here:
        Annuler();
        //ChargerCombo();
    }//GEN-LAST:event_btnannulActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        facture();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbnumcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnumcomActionPerformed
        // TODO add your handling code here:
        AffichersurLabel();
        AffCaisse();
    }//GEN-LAST:event_cbnumcomActionPerformed

    private void tfrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrechercheActionPerformed

    private void tfdateactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdateactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdateactActionPerformed

    private void tablepaiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepaiemMouseClicked
        // TODO add your handling code here:
        i=tablepaiem.getSelectedRow();
        Deplacer(i);
        
        //click arakarakin'ny colonne ny tableau no mitondra ny isehoan'ny NOM
        NOM = tablepaiem.getValueAt(tablepaiem.getSelectedRow(), 2).toString();
        NOM2 = tablepaiem.getValueAt(tablepaiem.getSelectedRow(), 3).toString();
        DATE = tablepaiem.getValueAt(tablepaiem.getSelectedRow(), 8).toString();
        
    }//GEN-LAST:event_tablepaiemMouseClicked

    private void tfnomcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnomcliActionPerformed
        // TODO add your handling code here:
        tfnomcli.setVisible(false);
    }//GEN-LAST:event_tfnomcliActionPerformed

    private void cbmodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmodeActionPerformed

    private void tfrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfrechercheKeyReleased
        // TODO add your handling code here:
        Recherche1();
    }//GEN-LAST:event_tfrechercheKeyReleased

    
        private void Ajouter(){
        String numpaiem= tfnumpaiem.getText();
        String numcom= cbnumcom.getSelectedItem().toString();
        String nomcli= tfnomcli.getText();
        String prencli= tfprencli.getText();
        String nomact= tfnomact.getText();
        String typeact= tftypeact.getText();
        String dureact= tfdureact.getText();
        String dateact= tfdateact.getText();
        String datepay = ((JTextField)datepaiem.getDateEditor().getUiComponent()).getText();
        String modepaiem = cbmode.getSelectedItem().toString();
        String montant= tfmontant.getText();
        String moispaiem = tfmois.getSelectedItem().toString();
        
        ClassePaiement cl= new ClassePaiement( numpaiem, numcom, nomcli, prencli, nomact, typeact, dureact, dateact, datepay, modepaiem, montant,moispaiem);
        if((numcom.equals("")||nomcli.equals("")||prencli.equals("")||nomact.equals(""))||typeact.equals("")||dureact.equals("")||dateact.equals("")||datepay.equals("")||modepaiem.equals("")||montant.equals("")){
             JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
                GestPaiement  gd= new  GestPaiement();
                gd.insert(cl) ;
                SommeTotal();
                Caisse();
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
        
    }
    
    private void AffichersurTable(){
        String numpaiem= tfnumpaiem.getText();
        String numcom= cbnumcom.getSelectedItem().toString();
        String nomcli= tfnomcli.getText();
        String prencli= tfprencli.getText();
        String nomact= tfnomact.getText();
        String typeact= tftypeact.getText();
        String dureact= tfdureact.getText();
        String dateact= tfdateact.getText();
        String datepay = ((JTextField)datepaiem.getDateEditor().getUiComponent()).getText();
        String modepaiem= cbmode.getSelectedItem().toString();
        String montant= tfmontant.getText();
        String moispaiem = tfmois.getSelectedItem().toString();
        
        try {
	    dt.setRowCount(0);//vider la list 
            GestPaiement gd = new  GestPaiement();
	    Rs = gd.getAll();
	    while(Rs.next()){
                numpaiem = Rs.getString("NUM_PAIEM");
	        numcom = Rs.getString("NUM_COM");
                nomcli= Rs.getString("NOM_CLI");
                prencli= Rs.getString("PREN_CLI");
                nomact = Rs.getString("NOM_ACT");
                typeact = Rs.getString("TYPE_ACT");
                dureact = Rs.getString("DURE_ACT");
                dateact = Rs.getString("DATE_COM");
                datepay = Rs.getString("DATE_PAIEM");
                modepaiem = Rs.getString("MODE_PAIEM");
                montant = Rs.getString("MONTANT_PAYER");
                moispaiem = Rs.getString("MOIS_PAIM");
                
                               
                Object[] dep = {numpaiem, numcom, nomcli, prencli, nomact, typeact, dureact, dateact, datepay, modepaiem, montant, moispaiem} ;
	        dt.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    
    }
    
     private void ChargeTable(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt = new DefaultTableModel();
            dt.addColumn("ID paiement");
            dt.addColumn("ID commande");
            dt.addColumn("Nom");
            dt.addColumn("Prénom");
            dt.addColumn("Nom activité");
            dt.addColumn("Type activité");
            dt.addColumn("Durée activité");
            dt.addColumn("Date commande");
            dt.addColumn("Date paiement");
            dt.addColumn("Mode paiement");
            dt.addColumn("Montant à payer ");
            dt.addColumn("Mois du paiement ");
                   
            tablepaiem.setModel(dt);
	    AffichersurTable();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
     
        private void Modifier(){
        String numcom= cbnumcom.getSelectedItem().toString();
        String nomcli= tfnomcli.getText();
        String prencli= tfprencli.getText();
        String nomact= tfnomact.getText();
        String typeact= tftypeact.getText();
        String dureact= tfdureact.getText();
        String dateact= tfdateact.getText();
        String datepay = ((JTextField)datepaiem.getDateEditor().getUiComponent()).getText();
        String numpaiem= tfnumpaiem.getText();
        String modepaiem= cbmode.getSelectedItem().toString();
        String montant= tfmontant.getText();
        String moispaiem= tfmois.getSelectedItem().toString();
        
        ClassePaiement cl= new ClassePaiement(numpaiem,numcom, nomcli, prencli, nomact, typeact, dureact, dateact, datepay, modepaiem, montant, moispaiem);
        if (numcom.equals("")||(nomcli.equals("")||prencli.equals("")||nomact.equals(""))||typeact.equals("")||dureact.equals("")||dateact.equals("")||datepay.equals("")||numpaiem.equals("")||modepaiem.equals("")||montant.equals("")){
             JOptionPane.showMessageDialog(null,"Veuillez cliquez sur le tableau");
        }else{
            try{
                GestPaiement ge = new GestPaiement() ;
                    ge.update(cl.getNumPaiem(),cl) ;
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
        
    }
        
     /*private void Supprimer(){
        String numcom= cbnumcom.getSelectedItem().toString();
        String nomcli= tfnomcli.getText();
        String prencli= tfprencli.getText();
        String nomact= tfnomact.getText();
        String typeact= tftypeact.getText();
        String dureact= tfdureact.getText();
        String dateact= tfdateact.getText();
        String datepay = ((JTextField)datepaiem.getDateEditor().getUiComponent()).getText();
        String numpaiem= tfnumpaiem.getText();
        String modepaiem=  cbmode.getSelectedItem().toString();
        String montant= tfmontant.getText();
        String moispaiem=  tfmois.getSelectedItem().toString();
        
        ClassePaiement cl= new ClassePaiement(numcom, nomcli, prencli, nomact, typeact, dureact, dateact, datepay, numpaiem, modepaiem, montant,moispaiem);
        if (numcom.equals("")||(nomcli.equals("")||prencli.equals("")||nomact.equals(""))||typeact.equals("")||dureact.equals("")||dateact.equals("")||datepay.equals("")||numpaiem.equals("")||modepaiem.equals("")||montant.equals("")){
             JOptionPane.showMessageDialog(null,"Veuillez cliquez sur le tableau");
        }else{
            try{
                GestPaiement ge = new GestPaiement() ;
                    ge.delete(cl.getNumPaiem());
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de suppression\n"+e); 
             }
        }
        
    }*/
        
           private void Supprimer(){
        String numcom= cbnumcom.getSelectedItem().toString();
        String nomcli= tfnomcli.getText();
        String prencli= tfprencli.getText();
        String nomact= tfnomact.getText();
        String typeact= tftypeact.getText();
        String dureact= tfdureact.getText();
        String dateact= tfdateact.getText();
        String datepay = ((JTextField)datepaiem.getDateEditor().getUiComponent()).getText();
        String numpaiem= tfnumpaiem.getText();
        String modepaiem= cbmode.getSelectedItem().toString();
        String montant= tfmontant.getText();
        String moispaiem= tfmois.getSelectedItem().toString();
        
        ClassePaiement cl= new ClassePaiement(numpaiem,numcom, nomcli, prencli, nomact, typeact, dureact, dateact, datepay, modepaiem, montant, moispaiem);
        if (numcom.equals("")||(nomcli.equals("")||prencli.equals("")||nomact.equals(""))||typeact.equals("")||dureact.equals("")||dateact.equals("")||datepay.equals("")||numpaiem.equals("")||modepaiem.equals("")||montant.equals("")){
            JOptionPane.showMessageDialog(null,"Veuillez cliquer sur le tableau ");
        }else{
            //int rep=JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION);
            try{
                if(JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
                  
                    GestPaiement ge = new GestPaiement();
                    ge.delete(cl.getNumPaiem());
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erreur de suppression"+e); 
            }
        }
    }
     
     
    private void Annuler(){
        cbnumcom.setSelectedItem("Choisir un numéro");
        tfnomcli.setText("");
        tfprencli.setText("");
        tfnomact.setText("");
        tftypeact.setText("");
        tfdureact.setText("");
        tfdateact.setText("");
        datepaiem.setCalendar(null);
        tfnumpaiem.setText("");
        cbmode.setSelectedItem("");
        tfmontant.setText("");
        tfmois.setSelectedItem("01(Jan)");
    }
    
    private void Deplacer(int i) {
        try {
            //((JTextField)date.getDateEditor().getUiComponent()).setText(tabrec.getValueAt(i,0).toString());
            tfnumpaiem.setText(tablepaiem.getValueAt(i, 0).toString());
            cbnumcom.setSelectedItem(tablepaiem.getValueAt(i, 1).toString());
            tfnomcli.setText(tablepaiem.getValueAt(i, 2).toString());
            tfprencli.setText(tablepaiem.getValueAt(i, 3).toString());
            tfnomact.setText(tablepaiem.getValueAt(i, 4).toString());
            tftypeact.setText(tablepaiem.getValueAt(i, 5).toString());
            tfdureact.setText(tablepaiem.getValueAt(i, 6).toString());
            tfdateact.setText(tablepaiem.getValueAt(i, 7).toString());
            ((JTextField)datepaiem.getDateEditor().getUiComponent()).setText(tablepaiem.getValueAt(i, 8).toString());
            cbmode.setSelectedItem(tablepaiem.getValueAt(i,9).toString());
            tfmontant.setText(tablepaiem.getValueAt(i, 10).toString());   
            tfmois.setSelectedItem(tablepaiem.getValueAt(i,11).toString());
        }
        catch (Exception e) {
        }
        
    } 
    
    private void ChargerCombo(){
          try{
                GestCommande gd=new GestCommande();
                Rs=gd.ChargerCombo();
                
                    while(Rs.next()){
                        cbnumcom.addItem(Rs.getString("NUM_COM"));
                    }
                    Rs.close();
           }catch(Exception e){
                   JOptionPane.showMessageDialog(null,"Veuillez saisir les informations coçernant le département\n"+e);
	   }
    }
           
       private void AffichersurLabel(){
        String numcom= (String)cbnumcom.getSelectedItem().toString();
        String nomcli = tfnomcli.getText();
        String prencli = tfprencli.getText();
        String datecom = tfdateact.getText();
        String nomact = tfnomact.getText();
        String typeact = tftypeact.getText();
        String titreact =tfdateact.getText();
        String dureact = tfdureact.getText();
        String dateact = tfdateact.getText();
        String montant = tfmontant.getText();
        String fin = tfmontant.getText();
 
         
        try { 
            ClasseCommander cl = new ClasseCommander(numcom, nomcli, prencli, datecom, nomact, titreact, typeact, dateact, fin, dureact, montant);
                                  
            GestCommande gd = new  GestCommande();
	    Rs = gd.TFChargerCombo(cl.getIdCom());
	    while(Rs.next()){
	        numcom = Rs.getString("NUM_COM");
                nomcli = Rs.getString("NOM_CLI");
                prencli = Rs.getString("PREN_CLI");
                nomact = Rs.getString("NOM_ACT");
                typeact = Rs.getString("TYPE_ACT");
                dureact = Rs.getString("DURE_ACT");
                dateact = Rs.getString("DATE_COM");
                montant = Rs.getString("PRIX_COM");
            
            }
            cbnumcom.setSelectedItem(String.valueOf(numcom));
            tfnomcli.setText(String.valueOf(nomcli));
            tfprencli.setText(String.valueOf(prencli));
            tfnomact.setText(String.valueOf(nomact));
            tftypeact.setText(String.valueOf(typeact));
            tfdureact.setText(String.valueOf(dureact));
            tfdateact.setText(String.valueOf(dateact));
            tfmontant.setText(String.valueOf(montant));
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Connection echouée\n"+e);
        }
    }

    
    private void Caisse(){
        String numcom= cbnumcom.getSelectedItem().toString();
        String nomcli= tfnomcli.getText();
        String prencli= tfprencli.getText();
        String nomact= tfnomact.getText();
        String typeact= tftypeact.getText();
        String dureact= tfdureact.getText();
        String dateact= tfdateact.getText();
        String datepay = ((JTextField)datepaiem.getDateEditor().getUiComponent()).getText();
        String numpaiem= tfnumpaiem.getText();
        String modepaiem=  cbmode.getSelectedItem().toString();
        String montant= tfmontant.getText();
        String caisse = tfcaisse.getText();
        String caisse1 = tfcaisse1.getText();
        String moispaiem = tfmois.getSelectedItem().toString();
        

        
        ClasseCaisse cl = new ClasseCaisse(caisse);
        ClassePaiement cl2= new ClassePaiement( numpaiem, numcom, nomcli, prencli, nomact, typeact, dureact, dateact, datepay, modepaiem, montant, moispaiem);
        if((numcom.equals("")||nomcli.equals("")||prencli.equals("")||nomact.equals(""))||typeact.equals("")||dureact.equals("")||dateact.equals("")||datepay.equals("")||modepaiem.equals("")||montant.equals("")){
               JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
                GestCaisse  gd= new  GestCaisse();
                //gd.insert(cl, cl2.getPaim()) ;
                gd.update( cl, cl2.getMontantPayer());
            }catch(Exception e){
              //JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
    }
    
     public void AffCaisse(){
        try{    				
               Class.forName("com.mysql.jdbc.Driver");
                con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
                 St = con.createStatement();
               Rs=St.executeQuery("select sum(solde_caisse) from caisse");    
               

              while (Rs.next()) {
                   tfcaisse.setText(Rs.getString("sum(solde_caisse)"));
                   tfcaisse1.setText(Rs.getString("sum(solde_caisse)"));
            }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
    }
     
     public void SommeTotal(){          
            String a = tfmontant.getText();
            Integer a1=new Integer(a);
            int paim = a1.intValue();
            
            String b = tfcaisse.getText();
            Integer b1=new Integer(b);
            int caiss = b1.intValue();
            
            int tot = (int) (paim + caiss);
            String stot = new String();
            stot =String.valueOf(tot);
            tfcaisse1.setText(stot);
             //tfcaisse.setText(stot);
            
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajout;
    private javax.swing.JButton btnannul;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JComboBox cbmode;
    private javax.swing.JComboBox cbnumcom;
    private com.toedter.calendar.JDateChooser datepaiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labdateAct;
    private javax.swing.JTable tablepaiem;
    private javax.swing.JTextField tfcaisse;
    private javax.swing.JTextField tfcaisse1;
    private javax.swing.JTextField tfdateact;
    private javax.swing.JTextField tfdureact;
    private javax.swing.JComboBox tfmois;
    private javax.swing.JTextField tfmontant;
    private javax.swing.JTextField tfnomact;
    private javax.swing.JTextField tfnomcli;
    private javax.swing.JTextField tfnumpaiem;
    private javax.swing.JTextField tfprencli;
    private javax.swing.JTextField tfrecherche;
    private javax.swing.JTextField tftypeact;
    // End of variables declaration//GEN-END:variables

    private Connection con;
    private Statement St;
    private ResultSet Rs;
    private int i;
    private DefaultTableModel dt;
    
    private Statement stm;
    private ResultSet rs;
    private int R = 0;
     public String  NOM = "";
     public String  NOM2 = "";
     public String  DATE = "";
    public String  des = "";
    
    
    private void facture(){
          // TODO add your handling code here:
        int F = 0;
        //if (jRadioButton11.isSelected()) F = 0;
        //if (jRadioButton22.isSelected()) F = 1;
        
        String fichier = "C:\\Users\\MARCELLINA\\Desktop\\pdf/FACTURE_"+NOM+"_"+NOM2+"_"+DATE+".pdf";

        Font contenue = new Font(Font.FontFamily.HELVETICA, 8,
            Font.NORMAL);
        Font tete = new Font(Font.FontFamily.TIMES_ROMAN, 8,
            Font.BOLD);
        Font subfont = new Font(Font.FontFamily.TIMES_ROMAN, 9,
            Font.BOLD);
        Font sbfont = new Font(Font.FontFamily.TIMES_ROMAN, 8,
            Font.NORMAL);
        Font italic = new Font(Font.FontFamily.TIMES_ROMAN, 9,
            Font.ITALIC);
        //i_text i = new i_text();  
        //String datedep= ((JTextField)datepaiem.getDateEditor().getUiComponent()).getText();
        try {
         Class.forName("org.gjt.mm.mysql.Driver");
	 con =DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	 stm=con.createStatement(); 
         int rep=JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment imprimer l'enregistrment?","Confirmation",JOptionPane.YES_NO_OPTION);
         if(rep==JOptionPane.YES_OPTION){
        if (F==0) rs = stm.executeQuery("Select * From paiement where date_paiem = '"+DATE+"' and nom_cli='"+NOM+"' and pren_cli= '"+NOM2+"' ");
        
            com.itextpdf.text.Document document = new com.itextpdf.text.Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream(fichier));
            document.open();

            Paragraph titre = new Paragraph();
            //i.addEmptyLine(titre, 1);
            titre.add(new Paragraph("                                                                                        TELEVISION GIDEONA", subfont));
            titre.add(new Paragraph("                                                                                           La télé de l'avenir", italic));
            titre.add(new Paragraph("   ",subfont));
            titre.add(new Paragraph("REGION: HAUTE MATSIATRA", subfont));
            titre.add(new Paragraph("DISTRICT: FIANARANTSOA", subfont));
            titre.add(new Paragraph("COMMUNE URBAINE: FIANARANTSOA", subfont));
            titre.add(new Paragraph("   ",subfont));
            //i.addEmptyLine(titre, 2);
            titre.add(new Paragraph("                                                                                                             FACTURE", subfont));
//            titre.add(new Paragraph("                                                                                         TAXE SUR PUBLICITE ANNEE "+choice1.getSelectedItem(), subfont));
            titre.add(new Paragraph("   ",subfont));
            titre.add(new Paragraph("                                                                                               DOIT: "+NOM2 ,subfont ));
            titre.add(new Paragraph("   ",subfont));
            //i.addEmptyLine(titre, 1);
            /*Paragraph pied = new Paragraph();
            pied.add(new Paragraph("Il est prevu que, faute de paiement, dans le delais de DOUZE (12) JOURS, le contribuable est possible d'une amende de AR 20 000 en plus de la taxe.",sbfont));
            String le = jLabel1.getText();
            pied.add(new Paragraph("   ",subfont));
            pied.add(new Paragraph("                                                                                                                                                                                                Fait à Ambalavao le "+le,sbfont));
            pied.add(new Paragraph("                                                                                                                                                                                                          LE MAIRE",sbfont));*/
        int X;
            if(F==0)X = 10;
            else X = 8;
            PdfPTable table = new PdfPTable(X);
            PdfPTable tot = new PdfPTable(3);
            table.setWidthPercentage(100);
            tot.setWidthPercentage(100);

            PdfPCell cell;

            cell = new PdfPCell(new Phrase("Nom", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Prénom", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Activité", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Type", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Durée", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Mode Paiement", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
            
            if (F==0){
            cell = new PdfPCell(new Phrase("Num Commande", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);}

            cell = new PdfPCell(new Phrase("Date Commande", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
            
            if (F==0){
            cell = new PdfPCell(new Phrase("Date Paiement", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);}

            cell = new PdfPCell(new Phrase("Montant", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
            
            cell = new PdfPCell(new Phrase("", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tot.addCell(cell);
            
            cell = new PdfPCell(new Phrase("Total", tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tot.addCell(cell);  
            
            while(rs.next()){
                if (F==0){
                cell = new PdfPCell(new Phrase(rs.getString("nom_cli"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("pren_cli"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("nom_act"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("type_act"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("dure_act"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("mode_paiem"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("num_com"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("date_com"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("date_paiem"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);

                cell = new PdfPCell(new Phrase(rs.getString("montant_payer"), contenue));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
                }
                
            }
            
 try{
 if (F==0){rs = stm.executeQuery("Select sum(montant_payer) From paiement where date_paiem = '"+DATE+"' and nom_cli='"+NOM+"' and pren_cli= '"+NOM2+"'");
 while(rs.next()){
            cell = new PdfPCell(new Phrase(rs.getString("sum(montant_payer)"), tete));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tot.addCell(cell); 
 }
 } 
    }catch(Exception e){        
    }

            table.setLockedWidth(false);
            float y = 10;
            float y1 = 20;
            float y2 = 15;
            float y3 = 120;
            float y4 = 14;
            float a1[] = {y1,y1,y1,y2,y,y2,y2,y2,y2,y2};
            float a2[] = {y,y1,y1,y1,y1,y,y,y2};
            float b1[] = {y3,y4,y4};
            float b2[] = {100,y,y2};
            tot.setWidths(b1);
        if (F==0){
            tot.setWidths(b1);
            table.setWidths(a1);
        }else{
            tot.setWidths(b2); 
            table.setWidths(a2);
        }
            tot.setHorizontalAlignment(Element.ALIGN_RIGHT);
            document.add(titre);
            document.add(table);
            document.add(tot);
            //document.add(pied);
            document.close();
         }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }    //i.open_Pdf(fichier);
    
    
    private void Recherche1() {                                           
        String rech=tfrecherche.getText();
        String numcom= cbnumcom.getSelectedItem().toString();
        String nomcli= tfnomcli.getText();
        String prencli= tfprencli.getText();
        String nomact= tfnomact.getText();
        String typeact= tftypeact.getText();
        String dureact= tfdureact.getText();
        String dateact= tfdateact.getText();
        String datepay = ((JTextField)datepaiem.getDateEditor().getUiComponent()).getText();
        String numpaiem= tfnumpaiem.getText();
        String modepaiem=  cbmode.getSelectedItem().toString();
        String montant= tfmontant.getText();
        String caisse = tfcaisse.getText();
        String caisse1 = tfcaisse1.getText();
        String moispaiem = tfmois.getSelectedItem().toString();
        try{
            dt.setRowCount(0);
            Rs=St.executeQuery("SELECT * FROM paiement WHERE (NOM_CLI LIKE '%"+rech+"%' OR PREN_CLI LIKE '%"+rech+"%' OR MOIS_PAIM LIKE '%"+rech+"%' OR NUM_COM LIKE '%"+rech+"%' OR MONTANT_PAYER LIKE '%"+rech+"%' OR DURE_ACT LIKE '%"+rech+"%' OR MODE_PAIEM LIKE '%"+rech+"%' OR NUM_PAIEM LIKE '%"+rech+"%' OR DATE_COM LIKE '%"+rech+"%' OR DATE_PAIEM LIKE '%"+rech+"%')");
            i=0;
            while(Rs.next()){
                numpaiem = Rs.getString("NUM_PAIEM");
	        numcom = Rs.getString("NUM_COM");
                nomcli= Rs.getString("NOM_CLI");
                prencli= Rs.getString("PREN_CLI");
                nomact = Rs.getString("NOM_ACT");
                typeact = Rs.getString("TYPE_ACT");
                dureact = Rs.getString("DURE_ACT");
                dateact = Rs.getString("DATE_COM");
                datepay = Rs.getString("DATE_PAIEM");
                modepaiem = Rs.getString("MODE_PAIEM");
                montant = Rs.getString("MONTANT_PAYER");
                moispaiem = Rs.getString("MOIS_PAIM");
                
                               
                Object[] dep = {numpaiem, numcom, nomcli, prencli, nomact, typeact, dureact, dateact, datepay, modepaiem, montant, moispaiem} ;
	        dt.addRow(dep);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }

    
}
