/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaire;

import Classe.ClasseCommander;
import Gestion.GestClient;
import Gestion.GestCommande;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELLINA
 */
public class FormCommander extends javax.swing.JPanel {

    /**
     * Creates new form FormCommander
     */
    public FormCommander() {
        initComponents();
        ChargeTableClient();
        ChargeTableCom();
        paneldatepub.setVisible(false);
        tfnumcom.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfnumcom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        labnum = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecli = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfnomcli = new javax.swing.JTextField();
        tfprencli = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfdureact = new javax.swing.JTextField();
        tftitact = new javax.swing.JTextField();
        cbnomact = new javax.swing.JComboBox();
        cbtypeact = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tfprixcom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        datecom = new com.toedter.calendar.JDateChooser();
        labtit = new javax.swing.JLabel();
        labdure = new javax.swing.JLabel();
        labprix = new javax.swing.JLabel();
        paneldatepub = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        datefinact = new com.toedter.calendar.JDateChooser();
        paneldateact = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        dateact = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnajout = new javax.swing.JButton();
        btnmodif = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        btnannul = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablecom = new javax.swing.JTable();
        tfrecherche = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        tfnumcom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnumcomKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel3.setText("Numéro:");

        lab.setText("des");

        labnum.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        labnum.setForeground(new java.awt.Color(255, 0, 0));

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMMANDE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tablecli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablecli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecli);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel2.setText("Nom du client:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfnomcli, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfprencli))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnomcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfprencli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel5.setText("Nom:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, -1, 22));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel6.setText("Type:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 63, -1, 20));

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel7.setText("Titre:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 30, 40, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel9.setText("Durée:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 63, -1, 30));

        tfdureact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdureactKeyTyped(evt);
            }
        });
        jPanel3.add(tfdureact, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 63, 160, 30));

        tftitact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tftitactKeyTyped(evt);
            }
        });
        jPanel3.add(tftitact, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 30, 160, -1));

        cbnomact.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        cbnomact.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choisir une activité", "Emission", "Matraquage", "Spot publicitaire", "Ticker" }));
        cbnomact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnomactActionPerformed(evt);
            }
        });
        jPanel3.add(cbnomact, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 30, 135, -1));

        cbtypeact.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        cbtypeact.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Evangelique", "Non Evangelique" }));
        jPanel3.add(cbtypeact, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 63, 136, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel10.setText("Prix commande:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 20));

        tfprixcom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfprixcomKeyTyped(evt);
            }
        });
        jPanel3.add(tfprixcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 147, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel11.setText("Ariary");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 20));

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel12.setText("Ajourdhui le:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 6, -1, -1));

        datecom.setBackground(new java.awt.Color(255, 255, 255));
        datecom.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(datecom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1, 164, -1));

        labtit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labtit.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(labtit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 110, 20));

        labdure.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labdure.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(labdure, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 110, 21));

        labprix.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labprix.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(labprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 126, 20));

        paneldatepub.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel16.setText("Date fin activité:");

        datefinact.setBackground(new java.awt.Color(255, 255, 255));
        datefinact.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout paneldatepubLayout = new javax.swing.GroupLayout(paneldatepub);
        paneldatepub.setLayout(paneldatepubLayout);
        paneldatepubLayout.setHorizontalGroup(
            paneldatepubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldatepubLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datefinact, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );
        paneldatepubLayout.setVerticalGroup(
            paneldatepubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(datefinact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(paneldatepub, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 260, -1));

        paneldateact.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel8.setText("Date activité:");

        dateact.setBackground(new java.awt.Color(255, 255, 255));
        dateact.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout paneldateactLayout = new javax.swing.GroupLayout(paneldateact);
        paneldateact.setLayout(paneldateactLayout);
        paneldateactLayout.setHorizontalGroup(
            paneldateactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldateactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(dateact, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );
        paneldateactLayout.setVerticalGroup(
            paneldateactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dateact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(paneldateact, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 112, 270, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setText("Choix activité");

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel13.setText("Choisir un client");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnajout.setBackground(new java.awt.Color(255, 255, 255));
        btnajout.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnajout.setForeground(new java.awt.Color(0, 51, 255));
        btnajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajout.jpg"))); // NOI18N
        btnajout.setText("Ajouter");
        btnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutActionPerformed(evt);
            }
        });

        btnmodif.setBackground(new java.awt.Color(255, 255, 255));
        btnmodif.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnmodif.setForeground(new java.awt.Color(0, 51, 255));
        btnmodif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modif2.jpg"))); // NOI18N
        btnmodif.setText("Modifier");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        btnsuppr.setBackground(new java.awt.Color(255, 255, 255));
        btnsuppr.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnsuppr.setForeground(new java.awt.Color(0, 51, 255));
        btnsuppr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppr1.jpg"))); // NOI18N
        btnsuppr.setText("Supprimer");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });

        btnannul.setBackground(new java.awt.Color(255, 255, 255));
        btnannul.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnannul.setForeground(new java.awt.Color(0, 51, 255));
        btnannul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/annuler1.jpg"))); // NOI18N
        btnannul.setText("Annuler");
        btnannul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnajout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnsuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnannul, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnajout)
                .addComponent(btnmodif)
                .addComponent(btnsuppr)
                .addComponent(btnannul))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        tablecom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablecom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecomMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablecom);

        tfrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrechercheActionPerformed(evt);
            }
        });
        tfrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfrechercheKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel13)
                        .addGap(359, 359, 359)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutActionPerformed
        // TODO add your handling code here:
        Ajouter();
        ChargeTableCom();
        Annuler();
        
        
    }//GEN-LAST:event_btnajoutActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        // TODO add your handling code here:
        Modifier();
        ChargeTableCom();
        Annuler();
        
        
    }//GEN-LAST:event_btnmodifActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
        // TODO add your handling code here:
        Supprimer();
        ChargeTableCom();
        Annuler();
        
        
    }//GEN-LAST:event_btnsupprActionPerformed

    private void btnannulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulActionPerformed
        // TODO add your handling code here:
        Annuler();
        
    }//GEN-LAST:event_btnannulActionPerformed

    private void tablecliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecliMouseClicked
        // TODO add your handling code here:
        i=tablecli.getSelectedRow();
        DeplacerClient(i);
    }//GEN-LAST:event_tablecliMouseClicked

    private void tablecomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecomMouseClicked
        // TODO add your handling code here:
        i=tablecom.getSelectedRow();
        DeplacerCom(i);
    }//GEN-LAST:event_tablecomMouseClicked

    private void tfrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrechercheActionPerformed

    private void tftitactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tftitactKeyTyped
        // TODO add your handling code here:
        labtit.setText("Caractère invalide");
        String valeur = tftitact.getText().toString();
        int ln = valeur.length();
        if (tftitact.getText().matches("[A-Z,a-z,é,à,è,ù,ç,',â, ]*")) {
            tftitact.setText(valeur);
            labtit.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tftitact.setText(valeur);
            labtit.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tftitactKeyTyped

    private void tfprixcomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfprixcomKeyTyped
        // TODO add your handling code here:
            labprix.setText("Caractére invalide");
        String valeur = tfprixcom.getText().toString();
        int ln = valeur.length();
        if (tfprixcom.getText().matches("[0-9]*")) {
            tfprixcom.setText(valeur);
            labprix.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfprixcom.setText(valeur);
            labprix.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfprixcomKeyTyped

    private void tfdureactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdureactKeyTyped
        // TODO add your handling code here:
            labdure.setText("Caractère invalide");
        String valeur = tfdureact.getText().toString();
        int ln = valeur.length();
        if (tfdureact.getText().matches("[0-9,:]*")) {
            tfdureact.setText(valeur);
            labdure.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfdureact.setText(valeur);
            labdure.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfdureactKeyTyped

    private void tfnumcomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnumcomKeyTyped
        // TODO add your handling code here:
            labnum.setText("Caractère invalide");
        String valeur = tfnumcom.getText().toString();
        int ln = valeur.length();
        if (tfnumcom.getText().matches("[0-9]*")) {
            tfnumcom.setText(valeur);
            labnum.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfnumcom.setText(valeur);
            labnum.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfnumcomKeyTyped

    private void tfrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfrechercheKeyReleased
        // TODO add your handling code here:
        Recherche1();
    }//GEN-LAST:event_tfrechercheKeyReleased

    private void cbnomactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnomactActionPerformed
        // TODO add your handling code here:
        combo_select();
    }//GEN-LAST:event_cbnomactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajout;
    private javax.swing.JButton btnannul;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JComboBox cbnomact;
    private javax.swing.JComboBox cbtypeact;
    private com.toedter.calendar.JDateChooser dateact;
    private com.toedter.calendar.JDateChooser datecom;
    private com.toedter.calendar.JDateChooser datefinact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel labdure;
    private javax.swing.JLabel labnum;
    private javax.swing.JLabel labprix;
    private javax.swing.JLabel labtit;
    private javax.swing.JPanel paneldateact;
    private javax.swing.JPanel paneldatepub;
    private javax.swing.JTable tablecli;
    private javax.swing.JTable tablecom;
    private javax.swing.JTextField tfdureact;
    private javax.swing.JTextField tfnomcli;
    private javax.swing.JTextField tfnumcom;
    private javax.swing.JTextField tfprencli;
    private javax.swing.JTextField tfprixcom;
    private javax.swing.JTextField tfrecherche;
    private javax.swing.JTextField tftitact;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    private int i;
    
    private void AffichersurTableClient(){
        String nom = tfnomcli.getText();
        String pren = tfprencli.getText();
            
        try {
	    dt.setRowCount(0);//vider la list 
            GestClient gd = new  GestClient();
	    Rs = gd.getAll();
	    while(Rs.next()){
                nom = Rs.getString("NOM_CLI");
                pren = Rs.getString("PREN_CLI");
                               
                Object[] dep = {nom, pren} ;
	        dt.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    }
 
    private void ChargeTableClient(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt = new DefaultTableModel();
            dt.addColumn("Nom");
            dt.addColumn("Prénom");
                   
            tablecli.setModel(dt);
	    AffichersurTableClient();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
    
    private void DeplacerClient(int i) {
        try {
            //((JTextField)date.getDateEditor().getUiComponent()).setText(tabrec.getValueAt(i,0).toString());
            tfnomcli.setText(tablecli.getValueAt(i, 0).toString());
            tfprencli.setText(tablecli.getValueAt(i, 1).toString());
 
        }
        catch (Exception e) {
        }
        
    }
    
    private void Ajouter(){
        String id=tfnumcom.getText();
        String nomcli=tfnomcli.getText();
        String prencli=tfprencli.getText();
        String datecm = ((JTextField)datecom.getDateEditor().getUiComponent()).getText();
        String nomact = cbnomact.getSelectedItem().toString();
        String titreact=tftitact.getText();
        String typeact = cbtypeact.getSelectedItem().toString();
        String dateat = ((JTextField)dateact.getDateEditor().getUiComponent()).getText();
        String datefact = ((JTextField)datefinact.getDateEditor().getUiComponent()).getText();
        String dureact= tfdureact.getText();
        String prixcom= tfprixcom.getText();
        
        ClasseCommander cl= new ClasseCommander(id, nomcli, prencli, datecm, nomact, titreact, typeact, dateat, datefact, dureact, prixcom);
        if ((nomcli.equals("")||prencli.equals("")||datecm.equals("")||nomact.equals(""))||titreact.equals("")||typeact.equals("")||dateat.equals("")||dureact.equals("")||prixcom.equals("")){
             JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
                GestCommande  gd= new  GestCommande();
                gd.insert(cl) ;
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
    
    }
    
    private void AfficherSurTableCom(){
        String id=tfnumcom.getText();
        String nomcli=tfnomcli.getText();
        String prencli=tfprencli.getText();
        String datecm = ((JTextField)datecom.getDateEditor().getUiComponent()).getText();
        String nomact = cbnomact.getSelectedItem().toString();
        String titreact=tftitact.getText();
        String typeact = cbtypeact.getSelectedItem().toString();        
        String dateat = ((JTextField)dateact.getDateEditor().getUiComponent()).getText();
        String datefact = ((JTextField)datefinact.getDateEditor().getUiComponent()).getText();
        String dureact= tfdureact.getText();
        String prixcom= tfprixcom.getText();
        
        try {
	    dt.setRowCount(0);//vider la list
            GestCommande gd = new  GestCommande();
	    Rs = gd.getAll();
	    while(Rs.next()){
                id = Rs.getString("NUM_COM");
                nomcli = Rs.getString("NOM_CLI");
                prencli = Rs.getString("PREN_CLI");
                datecm = Rs.getString("DATE_COM");
                nomact = Rs.getString("NOM_ACT");
                titreact = Rs.getString("TITRE_ACT");
                typeact = Rs.getString("TYPE_ACT");
                dateat = Rs.getString("DATE_ACT");
                datefact = Rs.getString("DATE_FIN_ACT");
                dureact = Rs.getString("DURE_ACT");
                prixcom = Rs.getString("PRIX_COM");
                               
                Object[] dep = {id, nomcli, prencli, datecm, nomact, titreact, typeact, dateat, datefact, dureact, prixcom} ;
	        dt.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    
    }
    
     private void ChargeTableCom(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt = new DefaultTableModel();
            dt.addColumn("ID");
            dt.addColumn("Nom");
            dt.addColumn("Prénom");
            dt.addColumn("Date commande");
            dt.addColumn("Nom activité");
            dt.addColumn("Titre activité");
            dt.addColumn("Type activité");
            dt.addColumn("Date activité");
            dt.addColumn("Date fin activité");
            dt.addColumn("Durée activité");
            dt.addColumn("Prix commande");
                   
            tablecom.setModel(dt);
	    AfficherSurTableCom();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
     
        private void Modifier(){
        String id=tfnumcom.getText();
        String nomcli=tfnomcli.getText();
        String prencli=tfprencli.getText();
        String datecm = ((JTextField)datecom.getDateEditor().getUiComponent()).getText();
        String nomact = cbnomact.getSelectedItem().toString();
        String titreact=tftitact.getText();
        String typeact = cbtypeact.getSelectedItem().toString();
        String dateat = ((JTextField)dateact.getDateEditor().getUiComponent()).getText();
        String datefact = ((JTextField)datefinact.getDateEditor().getUiComponent()).getText();
        String dureact= tfdureact.getText();
        String prixcom= tfprixcom.getText();
        
        ClasseCommander cl= new ClasseCommander(id,nomcli, prencli, datecm, nomact, titreact, typeact, dateat, datefact, dureact, prixcom);
        if (id.equals("")||(nomcli.equals("")||prencli.equals("")||datecm.equals("")||nomact.equals(""))||titreact.equals("")||typeact.equals("")||dateat.equals("")||dureact.equals("")||prixcom.equals("")){
             JOptionPane.showMessageDialog(null,"Veuillez cliquer sur le tableau commande");
        }else{
            try{
                GestCommande ge = new GestCommande() ;
                    ge.update(cl.getIdCom(),cl) ;
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de mofification\n"+e); 
             }
        }
    
    }
    
        
    private void Supprimer(){
        String id=tfnumcom.getText();
        String nomcli=tfnomcli.getText();
        String prencli=tfprencli.getText();
        String datecm = ((JTextField)datecom.getDateEditor().getUiComponent()).getText();
        String nomact = cbnomact.getSelectedItem().toString();
        String titreact=tftitact.getText();
        String typeact = cbtypeact.getSelectedItem().toString();
        String dateat = ((JTextField)dateact.getDateEditor().getUiComponent()).getText();
        String datefact = ((JTextField)datefinact.getDateEditor().getUiComponent()).getText();
        String dureact= tfdureact.getText();
        String prixcom= tfprixcom.getText();
        
        ClasseCommander cl= new ClasseCommander(id,nomcli, prencli, datecm, nomact, titreact, typeact, dateat, datefact, dureact, prixcom);
        if (id.equals("")||(nomcli.equals("")||prencli.equals("")||datecm.equals("")||nomact.equals(""))||titreact.equals("")||typeact.equals("")||dateat.equals("")||dureact.equals("")||prixcom.equals("")){
             JOptionPane.showMessageDialog(null,"Veuillez cliquer sur le tableau commande");
        }else{
            try{
                GestCommande ge = new GestCommande() ;
                    ge.delete(cl.getIdCom());
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de supression\n"+e); 
             }
        }
    
    }
    
    private void Annuler(){
        tfnumcom.setText("");
        tfnomcli.setText("");
        tfprencli.setText("");
        datecom.setCalendar(null);
        cbnomact.setSelectedItem("Choisir une activité");
        tftitact.setText("");
        cbtypeact.setSelectedItem("");
        dateact.setCalendar(null);
        datefinact.setCalendar(null);
        tfdureact.setText("");
        tfprixcom.setText("");
    }
    
    
    private void DeplacerCom(int i) {
        try {
            tfnumcom.setText(tablecom.getValueAt(i, 0).toString());
            tfnomcli.setText(tablecom.getValueAt(i, 1).toString());
            tfprencli.setText(tablecom.getValueAt(i, 2).toString());
            ((JTextField)datecom.getDateEditor().getUiComponent()).setText(tablecom.getValueAt(i, 3).toString());
            cbnomact.setSelectedItem(tablecom.getValueAt(i,4).toString());
            tftitact.setText(tablecom.getValueAt(i, 5).toString());
            cbtypeact.setSelectedItem(tablecom.getValueAt(i,6).toString());
            ((JTextField)dateact.getDateEditor().getUiComponent()).setText(tablecom.getValueAt(i, 7).toString());
            ((JTextField)datefinact.getDateEditor().getUiComponent()).setText(tablecom.getValueAt(i, 8).toString());
            tfdureact.setText(tablecom.getValueAt(i, 9).toString());
            tfprixcom.setText(tablecom.getValueAt(i, 10).toString());
        }
        catch (Exception e) {
        }
        
    }
    
   private void Recherche1() {                                           
        String rech=tfrecherche.getText();
        String num = tfnumcom.getText();
        String nom = tfnomcli.getText();
        String pren = tfprencli.getText();
        String datecm = ((JTextField)datecom.getDateEditor().getUiComponent()).getText();
        String nomact = cbnomact.getSelectedItem().toString();
        String tit = tftitact.getText();
        String typeact = cbtypeact.getSelectedItem().toString();
        String dateat = ((JTextField)dateact.getDateEditor().getUiComponent()).getText();
        String datefact = ((JTextField)datefinact.getDateEditor().getUiComponent()).getText();
        String dur = tfdureact.getText();
        String prix = tfprixcom.getText();
        try{
            dt.setRowCount(0);
            Rs=St.executeQuery("SELECT * FROM commander WHERE (NOM_CLI LIKE '%"+rech+"%' OR PREN_CLI LIKE '%"+rech+"%' OR TITRE_ACT LIKE '%"+rech+"%' OR NUM_COM LIKE '%"+rech+"%' OR PRIX_COM LIKE '%"+rech+"%' OR DURE_ACT LIKE '%"+rech+"%')");
            i=0;
            while(Rs.next()){
                num = Rs.getString("NUM_COM");
                nom = Rs.getString("NOM_CLI");
                pren = Rs.getString("PREN_CLI");
                datecm = Rs.getString("DATE_COM");
                nomact = Rs.getString("NOM_ACT");
                tit = Rs.getString("TITRE_ACT");
                typeact = Rs.getString("TYPE_ACT");
                dateat = Rs.getString("DATE_ACT");
                datefact = Rs.getString("DATE_FIN_ACT");
                dur = Rs.getString("DURE_ACT");
                prix = Rs.getString("PRIX_COM");
                
                               
                Object[] dep = {num, nom, pren, datecm, nomact, tit, typeact, dateat, datefact, dur, prix} ;
	        dt.addRow(dep);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }
   
   public void combo_select(){
        String tff = cbnomact.getSelectedItem().toString();
        if (tff.equals("Spot publicitaire")){
            paneldatepub.setVisible(true);

        }
        else{
            paneldatepub.setVisible(false); 
        }
    }
   /*public void combo(){
        String tff = cbnomact.getSelectedItem().toString();
        if (tff.equals(tff)){
            lab.setText(tff);
        }
    }*/
}
