/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaire;

import Classe.ClasseClient;
import Gestion.GestClient;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELLINA
 */
public class FormClient extends javax.swing.JPanel {

    /**
     * Creates new form Form
     */
    public FormClient() {
        initComponents();
        ChargeTable();
        tfnum.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labnum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfnom = new javax.swing.JTextField();
        tftel = new javax.swing.JTextField();
        tfadr = new javax.swing.JTextField();
        tfpren = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecli = new javax.swing.JTable();
        tfrecherche = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnmodif = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        btnannul = new javax.swing.JButton();
        btnajout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labnom = new javax.swing.JLabel();
        labpren = new javax.swing.JLabel();
        labadr = new javax.swing.JLabel();
        labtel = new javax.swing.JLabel();

        tfnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnumKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel2.setText("Numéro:");

        labnum.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labnum.setForeground(new java.awt.Color(255, 0, 51));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A PROPOS D'UN CLIENT");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setText("Nom:");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setText("Prénom(s):");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel5.setText("Adresse:");

        tfnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnomKeyTyped(evt);
            }
        });

        tftel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftelActionPerformed(evt);
            }
        });
        tftel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tftelKeyTyped(evt);
            }
        });

        tfadr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfadrActionPerformed(evt);
            }
        });
        tfadr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfadrKeyTyped(evt);
            }
        });

        tfpren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprenActionPerformed(evt);
            }
        });
        tfpren.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfprenKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel6.setText("Téléphone:");

        tablecli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablecli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecli);

        tfrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrechercheActionPerformed(evt);
            }
        });
        tfrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfrechercheKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnmodif.setBackground(new java.awt.Color(255, 255, 255));
        btnmodif.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnmodif.setForeground(new java.awt.Color(0, 0, 255));
        btnmodif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modif2.jpg"))); // NOI18N
        btnmodif.setText("Modifier");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        btnsuppr.setBackground(new java.awt.Color(255, 255, 255));
        btnsuppr.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnsuppr.setForeground(new java.awt.Color(0, 0, 255));
        btnsuppr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppr1.jpg"))); // NOI18N
        btnsuppr.setText("Supprimer");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });

        btnannul.setBackground(new java.awt.Color(255, 255, 255));
        btnannul.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnannul.setForeground(new java.awt.Color(0, 0, 255));
        btnannul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/annuler1.jpg"))); // NOI18N
        btnannul.setText("Annuler");
        btnannul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulActionPerformed(evt);
            }
        });

        btnajout.setBackground(new java.awt.Color(255, 255, 255));
        btnajout.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnajout.setForeground(new java.awt.Color(0, 0, 255));
        btnajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajout.jpg"))); // NOI18N
        btnajout.setText("Ajouter");
        btnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnannul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnajout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnannul, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labnom.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labnom.setForeground(new java.awt.Color(255, 0, 51));

        labpren.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labpren.setForeground(new java.awt.Color(255, 0, 51));
        labpren.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                labprenKeyReleased(evt);
            }
        });

        labadr.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labadr.setForeground(new java.awt.Color(255, 0, 51));

        labtel.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labtel.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labpren, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(labnom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labadr, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labtel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labnom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(labpren, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labadr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labtel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfpren)
                                    .addComponent(tfadr)
                                    .addComponent(tftel)
                                    .addComponent(tfnom, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfnom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfpren, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfadr)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tftel)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tftelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelActionPerformed

    private void tfadrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfadrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfadrActionPerformed

    private void tfprenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfprenActionPerformed

    private void tablecliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecliMouseClicked
        // TODO add your handling code here:
        i=tablecli.getSelectedRow();
        Deplacer(i);
    }//GEN-LAST:event_tablecliMouseClicked

    private void tfrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrechercheActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfrechercheActionPerformed

    private void tfrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfrechercheKeyReleased

        Recherche1();
    }//GEN-LAST:event_tfrechercheKeyReleased

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        // TODO add your handling code here:
        Modifier();
        Annuler();
        ChargeTable();
    }//GEN-LAST:event_btnmodifActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
        // TODO add your handling code here:
        Supprimer();
        Annuler();
        ChargeTable();
    }//GEN-LAST:event_btnsupprActionPerformed

    private void btnannulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulActionPerformed
        // TODO add your handling code here:
        Annuler();
    }//GEN-LAST:event_btnannulActionPerformed

    private void btnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutActionPerformed
        // TODO add your handling code here:
        Ajouter();
        Annuler();
        ChargeTable();
    }//GEN-LAST:event_btnajoutActionPerformed

    private void tfnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnumKeyTyped
        // TODO add your handling code here:
           labnum.setText("Caractère invalide");
        String valeur = tfnum.getText().toString();
        int ln = valeur.length();
        if (tfnum.getText().matches("[0-9]*")) {
            tfnum.setText(valeur);
            labnum.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfnum.setText(valeur);
            labnum.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfnumKeyTyped

    private void tfnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnomKeyTyped
        // TODO add your handling code here:
         labnom.setText("Caractère invalide");
        String valeur = tfnom.getText().toString();
        int ln = valeur.length();
        if (tfnom.getText().matches("[A-Z]*")) {
            tfnom.setText(valeur);
            labnom.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfnom.setText(valeur);
            labnom.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfnomKeyTyped

    private void tfprenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfprenKeyTyped
        // TODO add your handling code here:
        labpren.setText("Caractère invalide");
        String valeur = tfpren.getText().toString();
        int ln = valeur.length();
        if (tfpren.getText().matches("[A-Z,a-z,é,à,è,ù,ç,',â, ]*")) {
            tfpren.setText(valeur);
            labpren.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfpren.setText(valeur);
            labpren.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfprenKeyTyped

    private void tfadrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfadrKeyTyped
        // TODO add your handling code here:
        labadr.setText("Caractère invalide");
        String valeur = tfadr.getText().toString();
        int ln = valeur.length();
        if (tfadr.getText().matches("[A-Z,a-z,0-9,é,à,è,ù,ç,',â,+,/,-,*, ]*")) {
            tfadr.setText(valeur);
            labadr.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfadr.setText(valeur);
            labadr.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfadrKeyTyped

    private void tftelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tftelKeyTyped
        // TODO add your handling code here:
           labtel.setText("Caractère invalide");
        String valeur = tftel.getText().toString();
        int ln = valeur.length();
        if (tftel.getText().matches("[0-9,+]*")) {
            tftel.setText(valeur);
            labtel.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tftel.setText(valeur);
            labtel.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tftelKeyTyped

    private void labprenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labprenKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_labprenKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajout;
    private javax.swing.JButton btnannul;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labadr;
    private javax.swing.JLabel labnom;
    private javax.swing.JLabel labnum;
    private javax.swing.JLabel labpren;
    private javax.swing.JLabel labtel;
    private javax.swing.JTable tablecli;
    private javax.swing.JTextField tfadr;
    private javax.swing.JTextField tfnom;
    private javax.swing.JTextField tfnum;
    private javax.swing.JTextField tfpren;
    private javax.swing.JTextField tfrecherche;
    private javax.swing.JTextField tftel;
    // End of variables declaration//GEN-END:variables

    private Connection con;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    private int i;
    private String numCli;
    private String nomCli;
    
    private void Ajouter(){
        String num = tfnum.getText();
        String nom = tfnom.getText();
        String pren = tfpren.getText();
        String adr = tfadr.getText();
        String tel = tftel.getText();
        
        ClasseClient cl= new ClasseClient(num, nom, pren, adr, tel);
        if ((nom.equals("")||pren.equals("")||adr.equals("")||tel.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
                GestClient  gd= new  GestClient();
                gd.insert(cl) ;
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
    }
    
    private void AffichersurTable(){
    String num = tfnum.getText();
    String nom = tfnom.getText();
    String pren = tfpren.getText();
    String adr = tfadr.getText();
    String tel = tftel.getText();
    
    try {
	    dt.setRowCount(0);//vider la list 
            GestClient gd = new  GestClient();
	    Rs = gd.getAll();
	    while(Rs.next()){
                num = Rs.getString("NUM_CLI");
                nom = Rs.getString("NOM_CLI");
                pren = Rs.getString("PREN_CLI");
                adr = Rs.getString("ADRESSE_CLI");
                tel = Rs.getString("TEL_CLI");
                
                               
                Object[] dep = {num, nom, pren, adr, tel} ;
	        dt.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    }
      
    
    private void ChargeTable(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt = new DefaultTableModel();
            dt.addColumn("ID");
            dt.addColumn("Nom");
            dt.addColumn("Prénom");
            dt.addColumn("Adresse");
            dt.addColumn("Téléphone");
            
                   
            tablecli.setModel(dt);
	    AffichersurTable();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
    
    private void Modifier(){
        String num = tfnum.getText();
        String nom = tfnom.getText();
        String pren = tfpren.getText();
        String adr = tfadr.getText();
        String tel = tftel.getText();
        
        ClasseClient cl= new ClasseClient(num, nom, pren, adr, tel);
        if (num.equals("")||(nom.equals("")||pren.equals("")||adr.equals("")||tel.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
            if(JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment modifier cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
                
                    GestClient ge = new GestClient() ;
                    ge.update(cl.getIdClient(),cl) ;
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erreur de modification \n"+e); 
            }
        }
   }
    
   private void Supprimer(){
        String num = tfnum.getText();
        String nom = tfnom.getText(); 
        String pren =tfpren.getText();
        String adr =tfadr.getText();
        String tel =tftel.getText();
        
            
        ClasseClient cl = new ClasseClient(num, nom, pren, adr, tel) ;
        if (num.equals("")||(nom.equals("")||(pren.equals(""))||(adr.equals(""))||(tel.equals("")))){
            JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s) svp");
        }else{
            //int rep=JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION);
            try{
                if(JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
                  
                    GestClient ge = new GestClient();
                    ge.delete(cl.getIdClient());
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erreur de suppression"+e); 
            }
        }
    } 
   
    private void Annuler(){
        tfnum.setText("");
        tfnom.setText("");
        tfpren.setText("");
        tfadr.setText("");
        tftel.setText("");
    }
 
    private void Deplacer(int i) {
        try {
            //((JTextField)date.getDateEditor().getUiComponent()).setText(tabrec.getValueAt(i,0).toString());
            tfnum.setText(tablecli.getValueAt(i, 0).toString());
            tfnom.setText(tablecli.getValueAt(i, 1).toString());
            tfpren.setText(tablecli.getValueAt(i, 2).toString());
            tfadr.setText(tablecli.getValueAt(i, 3).toString());
            tftel.setText(tablecli.getValueAt(i, 4).toString());
            
 
        }
        catch (Exception e) {
        }
        
    }
    
    private void Recherche1() {                                           
        String rech=tfrecherche.getText();
        String num = tfnum.getText();
        String nom = tfnom.getText();
        String pren = tfpren.getText();
        String adr = tfadr.getText();
        String tel = tftel.getText();
        try{
            dt.setRowCount(0);
            Rs=St.executeQuery("SELECT * FROM client WHERE (NOM_CLI LIKE '%"+rech+"%' OR PREN_CLI LIKE '%"+rech+"%' OR ADRESSE_CLI LIKE '%"+rech+"%' OR NUM_CLI LIKE '%"+rech+"%')");
            i=0;
            while(Rs.next()){
                num = Rs.getString("NUM_CLI");
                nom = Rs.getString("NOM_CLI");
                pren = Rs.getString("PREN_CLI");
                adr = Rs.getString("ADRESSE_CLI");
                tel = Rs.getString("TEL_CLI");
                
                               
                Object[] dep = {num, nom, pren, adr, tel} ;
	        dt.addRow(dep);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }
    

}
