/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaire;

import Classe.ClasseCaissier;
import Gestion.GestCaissier;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELLINA
 */
public class FormCaissier extends javax.swing.JPanel {

    /**
     * Creates new form Formcaissier
     */
    public FormCaissier() {
        initComponents();
        ChargeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfnum = new javax.swing.JTextField();
        tfnom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfpren = new javax.swing.JTextField();
        tffon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tftel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnajout1 = new javax.swing.JButton();
        btnmodif = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        btnannul = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfrecherche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labtel = new javax.swing.JLabel();
        labfon = new javax.swing.JLabel();
        labpren = new javax.swing.JLabel();
        labcin = new javax.swing.JLabel();
        labnom = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel7.setText("N° CIN Caissier:");

        tfnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnumKeyTyped(evt);
            }
        });

        tfnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnomActionPerformed(evt);
            }
        });
        tfnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnomKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel8.setText("Nom:");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel9.setText("Prénom(s):");

        tfpren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprenActionPerformed(evt);
            }
        });
        tfpren.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfprenKeyTyped(evt);
            }
        });

        tffon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tffonKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel10.setText("Fonction:");

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel11.setText("Téléphone:");

        tftel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tftelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfnom)
                    .addComponent(tfpren)
                    .addComponent(tffon)
                    .addComponent(tftel)
                    .addComponent(tfnum, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfnom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(tffon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tftel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfpren, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  A PROPOS D'UN CAISSIER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnajout1.setBackground(new java.awt.Color(255, 255, 255));
        btnajout1.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnajout1.setForeground(new java.awt.Color(0, 51, 255));
        btnajout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajout.jpg"))); // NOI18N
        btnajout1.setText("Ajouter");
        btnajout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajout1ActionPerformed(evt);
            }
        });

        btnmodif.setBackground(new java.awt.Color(255, 255, 255));
        btnmodif.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnmodif.setForeground(new java.awt.Color(0, 51, 255));
        btnmodif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modif2.jpg"))); // NOI18N
        btnmodif.setText("Modifier");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        btnsuppr.setBackground(new java.awt.Color(255, 255, 255));
        btnsuppr.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnsuppr.setForeground(new java.awt.Color(0, 51, 255));
        btnsuppr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppr1.jpg"))); // NOI18N
        btnsuppr.setText("Supprimer");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });

        btnannul.setBackground(new java.awt.Color(255, 255, 255));
        btnannul.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnannul.setForeground(new java.awt.Color(0, 51, 255));
        btnannul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/annuler1.jpg"))); // NOI18N
        btnannul.setText("Annuler");
        btnannul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmodif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnajout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnannul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnajout1)
                .addGap(18, 18, 18)
                .addComponent(btnmodif)
                .addGap(18, 18, 18)
                .addComponent(btnsuppr)
                .addGap(18, 18, 18)
                .addComponent(btnannul)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tfrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrechercheActionPerformed(evt);
            }
        });
        tfrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfrechercheKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(418, 418, 418)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(419, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(106, Short.MAX_VALUE)))
        );

        labtel.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labtel.setForeground(new java.awt.Color(255, 0, 0));

        labfon.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labfon.setForeground(new java.awt.Color(255, 0, 0));

        labpren.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labpren.setForeground(new java.awt.Color(255, 0, 0));

        labcin.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labcin.setForeground(new java.awt.Color(255, 0, 0));

        labnom.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        labnom.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labtel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labfon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labpren, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labcin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labnom, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labcin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(labnom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(labpren, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(labfon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(labtel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnumKeyTyped
     labcin.setText("Caractère invalide");
        String valeur = tfnum.getText().toString();
        int ln = valeur.length();
        if (tfnum.getText().matches("[0-9]*")) {
            tfnum.setText(valeur);
            labcin.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfnum.setText(valeur);
            labcin.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfnumKeyTyped

    private void tfnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnomActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfnomActionPerformed

    private void tfnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnomKeyTyped

          labnom.setText("Caractère invalide");
        String valeur = tfnom.getText().toString();
        int ln = valeur.length();
        if (tfnom.getText().matches("[A-Z]*")) {
            tfnom.setText(valeur);
            labnom.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfnom.setText(valeur);
            labnom.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfnomKeyTyped

    private void tfprenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfprenActionPerformed

    private void tfprenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfprenKeyTyped
    labpren.setText("Caractère invalide");
        String valeur = tfpren.getText().toString();
        int ln = valeur.length();
        if (tfpren.getText().matches("[A-Z,a-z,é,à,è,ù,ç,',â, ]*")) {
            tfpren.setText(valeur);
            labpren.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tfpren.setText(valeur);
            labpren.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tfprenKeyTyped

    private void tffonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tffonKeyTyped
         labfon.setText("Caractère invalide");
        String valeur = tffon.getText().toString();
        int ln = valeur.length();
        if (tffon.getText().matches("[A-Z,a-z,0-9]*")) {
            tffon.setText(valeur);
            labfon.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tffon.setText(valeur);
            labfon.setVisible(true);
            int val = 0;
        }
        
    }//GEN-LAST:event_tffonKeyTyped

    private void tftelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tftelKeyTyped
     labtel.setText("Caractère invalide");
        String valeur = tftel.getText().toString();
        int ln = valeur.length();
        if (tftel.getText().matches("[0-9,+]*")) {
            tftel.setText(valeur);
            labtel.setVisible(false);
        } else {
            valeur = valeur.substring(0, ln - 1);
            tftel.setText(valeur);
            labtel.setVisible(true);
            int val = 0;
        }
    }//GEN-LAST:event_tftelKeyTyped

    private void btnajout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajout1ActionPerformed
        // TODO add your handling code here:
        Ajouter();
        ChargeTable();
        Annuler();

    }//GEN-LAST:event_btnajout1ActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        // TODO add your handling code here:
        Modifier();
        ChargeTable();
        Annuler();
    }//GEN-LAST:event_btnmodifActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
        // TODO add your handling code here:
        Supprimer();
        ChargeTable();
        Annuler();
    }//GEN-LAST:event_btnsupprActionPerformed

    private void btnannulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulActionPerformed
        // TODO add your handling code here:
        Annuler();
    }//GEN-LAST:event_btnannulActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        i=jTable1.getSelectedRow();
        Deplacer(i);
    }//GEN-LAST:event_jTable1MouseClicked

    private void tfrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrechercheActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfrechercheActionPerformed

    private void tfrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfrechercheKeyReleased

        Recherche1();
    }//GEN-LAST:event_tfrechercheKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajout1;
    private javax.swing.JButton btnannul;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labcin;
    private javax.swing.JLabel labfon;
    private javax.swing.JLabel labnom;
    private javax.swing.JLabel labpren;
    private javax.swing.JLabel labtel;
    private javax.swing.JTextField tffon;
    private javax.swing.JTextField tfnom;
    private javax.swing.JTextField tfnum;
    private javax.swing.JTextField tfpren;
    private javax.swing.JTextField tfrecherche;
    private javax.swing.JTextField tftel;
    // End of variables declaration//GEN-END:variables
   private int i;
    private Connection con;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;

    
    private void Ajouter(){
        String num = tfnum.getText();
        String nom = tfnom.getText();
        String pren = tfpren.getText();
        String fon = tffon.getText();
        String tel = tftel.getText();
        
        
        
        ClasseCaissier cl = new ClasseCaissier(num, nom, pren, fon, tel) ;
        if (num.equals("")||(nom.equals("")||pren.equals("")||fon.equals("")||tel.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
                GestCaissier gd= new  GestCaissier();
                gd.insert(cl) ;
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
    }
    
     private void AffichersurTable(){
        String num = tfnum.getText();
        String nom = tfnom.getText();
        String pren = tfpren.getText();
        String fon = tffon.getText();
        String tel = tftel.getText();
        
        
            
        try {
	    dt.setRowCount(0);//vider la list 
            GestCaissier gd = new  GestCaissier();
	    Rs = gd.getAll();
	    while(Rs.next()){
	        num = Rs.getString("cin_caissier");
                nom = Rs.getString("nom_caissier");
                pren = Rs.getString("pren_caissier");
                fon = Rs.getString("fonction");
                tel = Rs.getString("telephone");
               
                
                               
                Object[] dep = {num, nom, pren, fon, tel} ;
	        dt.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    }
    
     
     
    private void ChargeTable(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt = new DefaultTableModel();
            dt.addColumn("N°CIN Caissier");
            dt.addColumn("Nom");
            dt.addColumn("Prénom(s)");
            dt.addColumn("Fonction");
            dt.addColumn("Téléphone");
                   
            jTable1.setModel(dt);
	    AffichersurTable();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
    
    
    private void Modifier(){
        String num = tfnum.getText();
        String nom = tfnom.getText();
        String pren = tfpren.getText();
        String fon = tffon.getText();
        String tel = tftel.getText();
        
        
        
        ClasseCaissier cl = new ClasseCaissier(num, nom, pren, fon, tel) ;
        if (num.equals("")||(nom.equals("")||pren.equals("")||fon.equals("")||tel.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez cliquer sur le tableau caissier");
        }else{
            //int rep=JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment modifier cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION);
            try{
                if(JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment modifier cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
                
                    GestCaissier ge = new GestCaissier();
                    ge.update(cl.getCinCaissier(),cl) ;
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erreur de modification \n"+e); 
            }
        }
    }
    
    private void Supprimer(){
       String num = tfnum.getText();
        String nom = tfnom.getText();
        String pren = tfpren.getText();
        String fon = tffon.getText();
        String tel = tftel.getText();
        
        
        
        ClasseCaissier cl = new ClasseCaissier(num, nom, pren, fon, tel) ;
        if (num.equals("")||(nom.equals("")||pren.equals("")||fon.equals("")||tel.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez cliquer sur le tableau caissier");
        }else{
            //int rep=JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION);
            try{
                if(JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer cet enregistrement?","confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
                  
                    GestCaissier ge = new GestCaissier();
                    ge.delete(cl.getCinCaissier());
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erreur de suppression"+e); 
            }
        }
    }
     
     
      private void Annuler(){
        tfnum.setText("");
        tfnom.setText("");
        tfpren.setText("");
        tffon.setText("");
        tftel.setText("");
    }
 
    private void Deplacer(int i) {
        try {
            //((JTextField)date.getDateEditor().getUiComponent()).setText(tabrec.getValueAt(i,0).toString());
            tfnum.setText(jTable1.getValueAt(i, 0).toString());
            tfnom.setText(jTable1.getValueAt(i, 1).toString());
            tfpren.setText(jTable1.getValueAt(i, 2).toString());
            tffon.setText(jTable1.getValueAt(i, 3).toString());
            tftel.setText(jTable1.getValueAt(i, 4).toString());
            
 
        }
        catch (Exception e) {
        }
        
    }
    
    
     private void Recherche1() {                                           
        String rech=tfrecherche.getText();
        String num = tfnum.getText();
        String nom = tfnom.getText();
        String pren = tfpren.getText();
        String adr = tffon.getText();
        String tel = tftel.getText();
        try{
            dt.setRowCount(0);
            Rs=St.executeQuery("SELECT * FROM caissier WHERE (nom_caissier LIKE '%"+rech+"%' OR pren_caissier LIKE '%"+rech+"%' OR fonction LIKE '%"+rech+"%' OR cin_caissier LIKE '%"+rech+"%')");
            i=0;
            while(Rs.next()){
                num = Rs.getString("cin_caissier");
                nom = Rs.getString("nom_caissier");
                pren = Rs.getString("pren_caissier");
                adr = Rs.getString("fonction");
                tel = Rs.getString("telephone");
                
                               
                Object[] dep = {num, nom, pren, adr, tel} ;
	        dt.addRow(dep);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }
    
}
