/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaire;

import Classe.ClasseEvaluation;
import Gestion.GestDepense;
import Gestion.GestEvaluation;
import Gestion.GestPaiement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELLINA
 */
public class FormEvaluation extends javax.swing.JPanel {

    /**
     * Creates new form FormDepense
     */
    public FormEvaluation() {
        initComponents();
        ChargeTablePaiement();
        ChargeTableDepense();
        ChargeTableEvalu();
        labdateAct.setText(dateActuel());
        AffCaisse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfdateEvalu = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        tfnum = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        labdateAct = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        tfcaisse = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnajout = new javax.swing.JButton();
        btnannul = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEvalu = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePaiem = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tftotalP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDep = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tftotalD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        tfdateRech2 = new com.toedter.calendar.JDateChooser();
        tfdateRech1 = new com.toedter.calendar.JDateChooser();
        btnRech2D = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EVALUATION");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel9.setText("Fait le:");

        tfdateEvalu.setDateFormatString("yyyy-MM-dd");

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel11.setText("N° d'évaluation:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(31, 31, 31)
                        .addComponent(tfnum, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdateEvalu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(tfdateEvalu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date actuelle", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        labdateAct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labdateAct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labdateAct, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labdateAct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caisse", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 13))); // NOI18N

        tfcaisse.setEditable(false);
        tfcaisse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfcaisse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcaisse.setText("0");

        jLabel8.setText("Ariary");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfcaisse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcaisse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        btnajout.setBackground(new java.awt.Color(255, 255, 255));
        btnajout.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnajout.setForeground(new java.awt.Color(0, 0, 255));
        btnajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajout.jpg"))); // NOI18N
        btnajout.setText("Ajouter");
        btnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutActionPerformed(evt);
            }
        });

        btnannul.setBackground(new java.awt.Color(255, 255, 255));
        btnannul.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        btnannul.setForeground(new java.awt.Color(0, 0, 255));
        btnannul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/annuler1.jpg"))); // NOI18N
        btnannul.setText("Annuler");
        btnannul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulActionPerformed(evt);
            }
        });

        tableEvalu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableEvalu);

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel12.setText("et");

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel13.setText("Recherche entre");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        tablePaiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePaiem);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("LISTE DE PAIEMENTS");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Total paiement:");

        tftotalP.setEditable(false);
        tftotalP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tftotalP.setText("0");
        tftotalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftotalPActionPerformed(evt);
            }
        });

        jLabel6.setText("AR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tftotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(90, 90, 90))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel3)
                .addContainerGap(179, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tftotalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        tableDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDep);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("LISTE DE DEPENSES");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Total dépense:");

        tftotalD.setEditable(false);
        tftotalD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tftotalD.setText("0");
        tftotalD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftotalDActionPerformed(evt);
            }
        });

        jLabel7.setText("AR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(tftotalD, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tftotalD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        tfdateRech2.setDateFormatString("yyyy-MM-dd");

        tfdateRech1.setDateFormatString("yyyy-MM-dd");

        btnRech2D.setBackground(new java.awt.Color(255, 255, 255));
        btnRech2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnRech2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRech2DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnannul, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnajout, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel13)
                        .addGap(34, 34, 34)
                        .addComponent(tfdateRech1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(tfdateRech2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRech2D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnajout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnannul))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfdateRech2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRech2D, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdateRech1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 563, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     private String dateActuel(){
        Date daty=new Date();
        String dat=DateFormat.getDateInstance().format(daty);
        return dat;
    }
    private void tftotalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftotalPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftotalPActionPerformed

    private void tftotalDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftotalDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftotalDActionPerformed

    private void btnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutActionPerformed
        // TODO add your handling code here:
        Ajouter();
        ChargeTableEvalu();
        
    }//GEN-LAST:event_btnajoutActionPerformed

    private void btnRech2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRech2DActionPerformed
        // TODO add your handling code here:
        Recherche_entre2_dateD();
        Recherche_entre2_dateP();
        Affiche_RechercheTot_P();
        Affiche_RechercheTot_D();
    }//GEN-LAST:event_btnRech2DActionPerformed

    private void btnannulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnannulActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRech2D;
    private javax.swing.JButton btnajout;
    private javax.swing.JButton btnannul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labdateAct;
    private javax.swing.JTable tableDep;
    private javax.swing.JTable tableEvalu;
    private javax.swing.JTable tablePaiem;
    private javax.swing.JTextField tfcaisse;
    private com.toedter.calendar.JDateChooser tfdateEvalu;
    private com.toedter.calendar.JDateChooser tfdateRech1;
    private com.toedter.calendar.JDateChooser tfdateRech2;
    private javax.swing.JTextField tfnum;
    private javax.swing.JTextField tftotalD;
    private javax.swing.JTextField tftotalP;
    // End of variables declaration//GEN-END:variables

    private Connection con;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    private DefaultTableModel dt2;
    private DefaultTableModel dt1;
    private int i;
    
    private void ChargeTablePaiement(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt = new DefaultTableModel();
            dt.addColumn("Date");
            dt.addColumn("Montant");
            
            tablePaiem.setModel(dt);
            AffichersurTablePaiement();
            Affiche_TotPaiement();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
    
    
    private void ChargeTableDepense(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt2 = new DefaultTableModel();
            dt2.addColumn("Date");
            dt2.addColumn("Montant");
            
            tableDep.setModel(dt2);
            AffichersurTableDepense();
            Affiche_TotDepense();
            
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
 
    private void AffichersurTablePaiement(){
        
        String dateact= tfnum.getText();
        String datepay = ((JTextField)tfdateEvalu.getDateEditor().getUiComponent()).getText();
        
        try {
	    dt.setRowCount(0);//vider la list 
            GestPaiement gd = new  GestPaiement();
	    Rs = gd.getAll();
	    while(Rs.next()){
                
                dateact = Rs.getString("DATE_PAIEM");
                datepay = Rs.getString("MONTANT_PAYER");
                
                               
                Object[] dep = {dateact, datepay} ;
	        dt.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    
    }
    
    private void AffichersurTableDepense(){
        
        String dateact2= tfnum.getText();
        String datepay2 = ((JTextField)tfdateEvalu.getDateEditor().getUiComponent()).getText();
        
        try {
	    dt2.setRowCount(0);//vider la list 
            GestDepense gd = new  GestDepense();
	    Rs = gd.getAll();
	    while(Rs.next()){
                
                dateact2 = Rs.getString("DATE_DEP");
                datepay2 = Rs.getString("MONTANT_DEP");
                
                               
                Object[] dep = {dateact2, datepay2} ;
	        dt2.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    
    }
    
    
    public void Affiche_TotDepense(){
        try{    				
               Class.forName("com.mysql.jdbc.Driver");
                con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
                 St = con.createStatement();
               Rs=St.executeQuery("select sum(MONTANT_DEP) from depense");    
               

              while (Rs.next()) {
                   tftotalD.setText(Rs.getString("sum(MONTANT_DEP)"));
            }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
    }
    
    
        public void Affiche_TotPaiement(){
        try{    				
               Class.forName("com.mysql.jdbc.Driver");
                con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
                 St = con.createStatement();
               Rs=St.executeQuery("select sum(MONTANT_PAYER) from paiement");    
               

              while (Rs.next()) {
                   tftotalP.setText(Rs.getString("sum(MONTANT_PAYER)"));
            }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
    }
        
    public void Affiche_RechercheTot_P(){
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

        int day2,month2,years2;
            years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
            month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
            day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);
        try{    				
               Class.forName("com.mysql.jdbc.Driver");
                con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
                 St = con.createStatement();
               Rs=St.executeQuery("select sum(MONTANT_PAYER) from paiement where DATE_PAIEM between '"+years1+"-"+month1+"-"+day1+"' and '"+years2+"-"+month2+"-"+day2+"'");    
               

              while (Rs.next()) {
                   tftotalP.setText(Rs.getString("sum(MONTANT_PAYER)"));
            }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
    }
    
   
 private void Recherche_entre2_dateP(){
     
   String dateact= tfnum.getText();
   String datepay = ((JTextField)tfdateEvalu.getDateEditor().getUiComponent()).getText();
    
  int day1,month1,years1;
   years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
   month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
   day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

  int day2,month2,years2;
   years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
   month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
   day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);
 try{
     
     dt.setRowCount(0);//vider la liste
     Rs=St.executeQuery("Select DATE_PAIEM, MONTANT_PAYER from paiement where DATE_PAIEM between '"+years1+"-"+month1+"-"+day1+"' and '"+years2+"-"+month2+"-"+day2+"'");
        i=0;
        while(Rs.next()){
                dateact = Rs.getString("DATE_PAIEM");
                datepay = Rs.getString("MONTANT_PAYER");
                
                Object[]pay={dateact,datepay};
                dt.addRow(pay);
                
        }
        i=i+1;
        if(dt.getColumnCount()==0){
            JOptionPane.showMessageDialog(null,"Aucun résultat\n");
            //AfficheDidp("");
        }else{
            i=0;
            
        }
   }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de recherche\n"+e);
     } 
 }
 
 
  private void Recherche_entre2_dateD(){
     
   String dateact2= tfnum.getText();
   String datepay2 = ((JTextField)tfdateEvalu.getDateEditor().getUiComponent()).getText();
    
  int day1,month1,years1;
   years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
   month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
   day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

  int day2,month2,years2;
   years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
   month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
   day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);
 try{
     dt2.setRowCount(0);//vider la liste
     Rs=St.executeQuery("Select DATE_DEP, MONTANT_DEP from depense where DATE_DEP between '"+years1+"-"+month1+"-"+day1+"' and '"+years2+"-"+month2+"-"+day2+"'");
        i=0;
        while(Rs.next()){
                dateact2 = Rs.getString("DATE_DEP");
                datepay2 = Rs.getString("MONTANT_DEP");
                
                Object[]pay={dateact2,datepay2};
                dt2.addRow(pay);
        }
        i=i+1;
        if(dt2.getColumnCount()==0){
            JOptionPane.showMessageDialog(null,"Aucun résultat\n");
            //AfficheDidp("");
        }else{
            i=0;
            
        }
   }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de recherche\n"+e);
     } 
 }
  
  
     public void Affiche_RechercheTot_D(){
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

        int day2,month2,years2;
            years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
            month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
            day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);
        try{    				
               Class.forName("com.mysql.jdbc.Driver");
                con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
                 St = con.createStatement();
               Rs=St.executeQuery("select sum(MONTANT_DEP) from depense where DATE_DEP between '"+years1+"-"+month1+"-"+day1+"' and '"+years2+"-"+month2+"-"+day2+"'");    
               

              while (Rs.next()) {
                   tftotalD.setText(Rs.getString("sum(MONTANT_DEP)"));
            }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
    }
     
     
 public void AffCaisse(){
        try{    				
               Class.forName("com.mysql.jdbc.Driver");
                con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
                 St = con.createStatement();
               Rs=St.executeQuery("select sum(solde_caisse) from caisse");    
               

              while (Rs.next()) {
                   tfcaisse.setText(Rs.getString("sum(solde_caisse)"));
                    }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
    }
 
 private void Ajouter(){
        String num = tfnum.getText();
        String datevalu = ((JTextField)tfdateEvalu.getDateEditor().getUiComponent()).getText();
        String datrech1 = ((JTextField)tfdateRech1.getDateEditor().getUiComponent()).getText();
        String datrech2 = ((JTextField)tfdateRech2.getDateEditor().getUiComponent()).getText();
        String totpaiem = tftotalP.getText();
        String totdep = tftotalD.getText();
        String soldcaisse = tfcaisse.getText();
        
        ClasseEvaluation cl= new ClasseEvaluation(num, datevalu, datrech1, datrech2, totpaiem, totdep, soldcaisse);
        if (num.equals("")||(datevalu.equals("")||datrech1.equals("")||datrech2.equals("")||totpaiem.equals("")||totdep.equals("")||soldcaisse.equals(""))){
             JOptionPane.showMessageDialog(null,"Veuillez remplir le(s) champ(s) vide(s)");
        }else{
            try{
                GestEvaluation gd= new  GestEvaluation();
                gd.insert(cl) ;
            }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Erreur de l'enregistrement\n"+e); 
             }
        }
    }
 
 private void AffichersurTable(){
        String num = tfnum.getText();
        String datevalu = ((JTextField)tfdateEvalu.getDateEditor().getUiComponent()).getText();
        String datrech1 = ((JTextField)tfdateRech1.getDateEditor().getUiComponent()).getText();
        String datrech2 = ((JTextField)tfdateRech2.getDateEditor().getUiComponent()).getText();
        String totpaiem = tftotalP.getText();
        String totdep = tftotalD.getText();
        String soldcaisse = tfcaisse.getText();
    
    try {
	    dt1.setRowCount(0);//vider la list 
            GestEvaluation gd = new  GestEvaluation();
	    Rs = gd.getAll();
	    while(Rs.next()){
                num = Rs.getString("num_evalu");
                datevalu = Rs.getString("date_evalu");
                datrech1 = Rs.getString("date_rech1");
                datrech2 = Rs.getString("date_rech2");
                totpaiem = Rs.getString("total_paiem");
                totdep = Rs.getString("total_dep");
                soldcaisse = Rs.getString("solde_final_caisse");
                
                               
                Object[] dep = {num, datevalu, datrech1, datrech2, totpaiem, totdep, soldcaisse} ;
	        dt1.addRow(dep);
	    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Affichage sur le Tableau echouée\n"+e);
        }
    }
      
    
    private void ChargeTableEvalu(){
        try{
            Class.forName("org.gjt.mm.mysql.Driver");  
	    con = DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
	    St = con.createStatement();
            dt1 = new DefaultTableModel();
            dt1.addColumn("ID");
            dt1.addColumn("Date");
            dt1.addColumn("Date debut recherche");
            dt1.addColumn("Date fin recherche");
            dt1.addColumn("Total paiement");
            dt1.addColumn("Total depense");
            dt1.addColumn("Solde Final caisse");
            
            
                   
            tableEvalu.setModel(dt1);
            AffichersurTable();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
    


}