/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Listes;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELLINA
 */
public class ListeDepense extends javax.swing.JPanel {

    /**
     * Creates new form ListeDepense
     */
    public ListeDepense() {
        initComponents();
         radio_function();
         ChargeTableDepense();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lab_et = new javax.swing.JLabel();
        tfdateRech2 = new com.toedter.calendar.JDateChooser();
        tfdateRech1 = new com.toedter.calendar.JDateChooser();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        panImprimer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDep = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tftotalD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(997, 653));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Recherche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Recherche");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Entre");

        lab_et.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lab_et.setText("et");

        tfdateRech2.setDateFormatString("yyyy-MM-dd");

        tfdateRech1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfdateRech1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lab_et, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfdateRech2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_et, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfdateRech2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfdateRech1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRadioButton2.setText("Entre deux dates");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRadioButton1.setText("Une seule date");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Liste des dépenses ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(417, 417, 417))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 255));
        jButton5.setText("Imprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 255));
        jButton6.setText("Annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        panImprimer.setBackground(new java.awt.Color(255, 255, 255));

        tableDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12", "vhjvv", "hgjgg", "hgfhf"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDep);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Total dépenses:");

        tftotalD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftotalDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Ariary");

        javax.swing.GroupLayout panImprimerLayout = new javax.swing.GroupLayout(panImprimer);
        panImprimer.setLayout(panImprimerLayout);
        panImprimerLayout.setHorizontalGroup(
            panImprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panImprimerLayout.createSequentialGroup()
                .addGroup(panImprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panImprimerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tftotalD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(panImprimerLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)))
                .addGap(109, 109, 109))
        );
        panImprimerLayout.setVerticalGroup(
            panImprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panImprimerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panImprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftotalD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jRadioButton1)
                        .addGap(47, 47, 47)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Recherche2();
        Affiche_RechercheTot_D();
        ;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Recherche1();
        Affiche_Recherche1Tot_D();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        radio_select();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        radio_select();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:       
        imprimer();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tftotalDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftotalDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftotalDActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_et;
    private javax.swing.JPanel panImprimer;
    private javax.swing.JTable tableDep;
    private com.toedter.calendar.JDateChooser tfdateRech1;
    private com.toedter.calendar.JDateChooser tfdateRech2;
    private javax.swing.JTextField tftotalD;
    // End of variables declaration//GEN-END:variables
private Connection con;
    private Statement stm;
    private ResultSet rs;
    private int i;
    private DefaultTableModel dt;
    
    private String id;
    private String datedep;
    private String montant;
    private String motif;
    
     private void ChargeTableDepense(){
        try{
             Class.forName("org.gjt.mm.mysql.Driver");
            //Etalissement de la connexion à localhost et à la base de données gets_etudiant
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse", "root", "");
            stm = (Statement) con.createStatement(); 
            dt = new DefaultTableModel();
            dt.addColumn("ID");          
            dt.addColumn("Date dépense");
            dt.addColumn("Montant");
            dt.addColumn("Motif");
          
            tableDep.setModel(dt);

	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
     
       private void Recherche1() { 
          
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);
                                        
       
        try{
            dt.setRowCount(0);
            rs=stm.executeQuery("select * from depense where date_dep = '"+years1+"-"+month1+"-"+day1+"'");    
               i=0;
            while(rs.next()){
                 id = rs.getString("num_dep");
                datedep = rs.getString("date_dep");
                montant = rs.getString("montant_dep");
                motif = rs.getString("motif_dep");

                
                Object[] materiel = {id,datedep,montant,motif};
                dt.addRow(materiel);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }
       
       
            private void Recherche2() { 
          
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

        int day2,month2,years2;
            years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
            month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
            day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);                                       
       
        try{
            dt.setRowCount(0);
            rs=stm.executeQuery("select * from depense where date_dep between '"+years1+"-"+month1+"-"+day1+"' and '"+years2+"-"+month2+"-"+day2+"'");    
               i=0;
            while(rs.next()){
                 id = rs.getString("num_dep");
                datedep = rs.getString("date_dep");
                montant = rs.getString("montant_dep");
                motif = rs.getString("motif_dep");
        
                Object[] materiel = {id, datedep, montant, motif};
                dt.addRow(materiel);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }
    
    
private ButtonGroup radioGroup=new ButtonGroup();
      private void radio_function(){
        jRadioButton1.setSelected(true);
        tfdateRech2.setVisible(false);
        jButton1.setVisible(false);
        lab_et.setVisible(false);
        
        radioGroup.add(jRadioButton1);
        radioGroup.add(jRadioButton2);
    }
     public void radio_select(){
        if(jRadioButton1.isSelected()){
            jButton3.setVisible(true);
            jButton1.setVisible(false);
            tfdateRech1.setVisible(true);
            tfdateRech2.setVisible(false);
            lab_et.setVisible(false);
        }
      
        if(jRadioButton2.isSelected()){
            jButton3.setVisible(false);
            jButton1.setVisible(true);
            tfdateRech1.setVisible(true);
            tfdateRech2.setVisible(true);
            lab_et.setVisible(true);
        }
    }
     
     
  private void imprimer(){
   try{
        MessageFormat header=new MessageFormat("LISTE DES DEPENSES");
        MessageFormat footer =new MessageFormat("Page{0,number,integer}");
        tableDep.print(JTable.PrintMode.FIT_WIDTH,header,footer);
    }catch(Exception e){
       System.out.format("cannot print%s%n");
       e.getMessage();
    }
   }
     
     
        public void Affiche_RechercheTot_D(){
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

        int day2,month2,years2;
            years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
            month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
            day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);
        try{    				
              Class.forName("com.mysql.jdbc.Driver");
              con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse", "root", "");
              stm = (Statement) con.createStatement(); 
              rs=stm.executeQuery("select sum(MONTANT_DEP) from depense where DATE_DEP between '"+years1+"-"+month1+"-"+day1+"' and '"+years2+"-"+month2+"-"+day2+"'");    
               

              while (rs.next()) {
                   tftotalD.setText(rs.getString("sum(MONTANT_DEP)"));
            }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
        
        
        
    }
    
        public void Affiche_Recherche1Tot_D(){
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);
        try{    				
              Class.forName("com.mysql.jdbc.Driver");
              con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse", "root", "");
              stm = (Statement) con.createStatement(); 
              rs=stm.executeQuery("select sum(MONTANT_DEP) from depense where DATE_DEP ='"+years1+"-"+month1+"-"+day1+"'");    
               

              while (rs.next()) {
                   tftotalD.setText(rs.getString("sum(MONTANT_DEP)"));
            }
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
        
        
        
    }


}
