/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Listes;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELLINA
 */
public class ListePaiement extends javax.swing.JPanel {

    /**
     * Creates new form ListePaiements
     */
    public ListePaiement() {
        initComponents();
         //charge();
         radio_function();
         ChargeTablePaiement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepaiem = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tftotalP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lab_et = new javax.swing.JLabel();
        tfdateRech2 = new com.toedter.calendar.JDateChooser();
        tfdateRech1 = new com.toedter.calendar.JDateChooser();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(997, 653));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("Imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);
        jButton2.setBounds(670, 390, 90, 23);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 255));
        jButton4.setText("Annuler");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);
        jButton4.setBounds(520, 390, 77, 23);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tablepaiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablepaiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepaiemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablepaiem);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setText("Total paiements:");

        tftotalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftotalPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setText("Ariary");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tftotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tftotalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel3);
        jPanel3.setBounds(40, 10, 760, 370);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Recherche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("Recherche");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel1.setText("Entre");

        lab_et.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        lab_et.setText("et");

        tfdateRech2.setDateFormatString("yyyy-MM-dd");

        tfdateRech1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfdateRech1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lab_et, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfdateRech2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_et, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfdateRech2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfdateRech1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jRadioButton2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jRadioButton2.setText("Entre deux dates");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jRadioButton1.setText("Une seule date");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Liste des paiements ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(381, 381, 381))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablepaiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepaiemMouseClicked

    }//GEN-LAST:event_tablepaiemMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        imprimer();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Recherche2();
        Affiche_RechercheTot_P();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Recherche1();
        Affiche_Recherche1Tot_P();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        radio_select();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        radio_select();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tftotalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftotalPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftotalPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lab_et;
    private javax.swing.JTable tablepaiem;
    private com.toedter.calendar.JDateChooser tfdateRech1;
    private com.toedter.calendar.JDateChooser tfdateRech2;
    private javax.swing.JTextField tftotalP;
    // End of variables declaration//GEN-END:variables

    private Connection con;
    private Statement stm;
    private ResultSet rs;
    private int i;
    private DefaultTableModel dt;
    
    private String id;
    private String nomact;
    private String typeact;
    private String dureact;
    private String datepaiem;
    private String modepaiem;
    private String montant;
    
    
        
     private void ChargeTablePaiement(){
        try{
             Class.forName("org.gjt.mm.mysql.Driver");
            //Etalissement de la connexion à localhost et à la base de données gets_etudiant
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse", "root", "");
            stm = (Statement) con.createStatement(); 
            dt = new DefaultTableModel();
            dt.addColumn("ID");          
            dt.addColumn("NomAct");
            dt.addColumn("TypeAct");
            dt.addColumn("DuréeAct");
            dt.addColumn("Date paiement");
            dt.addColumn("Montant à payer ");
          
            tablepaiem.setModel(dt);
            
            //AffichersurTablePaiement();
            //Affiche_TotPaiement();
	}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Chargement de la Table echouée\n"+e);
	}
    }
     
     
     
      private ButtonGroup radioGroup=new ButtonGroup();
      private void radio_function(){
        jRadioButton1.setSelected(true);
        tfdateRech2.setVisible(false);
        jButton1.setVisible(false);
        lab_et.setVisible(false);
        
        radioGroup.add(jRadioButton1);
        radioGroup.add(jRadioButton2);
    }
     public void radio_select(){
        if(jRadioButton1.isSelected()){
            jButton3.setVisible(true);
            jButton1.setVisible(false);
            tfdateRech1.setVisible(true);
            tfdateRech2.setVisible(false);
            lab_et.setVisible(false);
        }
      
        if(jRadioButton2.isSelected()){
            jButton3.setVisible(false);
            jButton1.setVisible(true);
            tfdateRech1.setVisible(true);
            tfdateRech2.setVisible(true);
            lab_et.setVisible(true);
        }
    }

      private void Recherche1() { 
          
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

        /*int day2,month2,years2;
            years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
            month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
            day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);*/                                        
       
        try{
            dt.setRowCount(0);
            rs=stm.executeQuery("select num_paiem, nom_act, type_act, dure_act, date_paiem, montant_payer from paiement where DATE_PAIEM = '"+years1+"-"+month1+"-"+day1+"'");    
               i=0;
            while(rs.next()){
                 id = rs.getString("num_paiem");
                nomact = rs.getString("nom_act");
                typeact = rs.getString("type_act");
                dureact = rs.getString("dure_act");
                datepaiem = rs.getString("date_paiem");
                montant = rs.getString("montant_payer");
  
                
                Object[] materiel = {id,nomact,typeact,dureact,datepaiem,montant};
                dt.addRow(materiel);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }
      
      
            private void Recherche2() { 
          
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

        int day2,month2,years2;
            years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
            month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
            day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);                                       
       
        try{
            dt.setRowCount(0);
            rs=stm.executeQuery("select num_paiem, nom_act, type_act, dure_act, date_paiem, montant_payer from paiement where DATE_PAIEM between '"+years1+"-"+month1+"-"+day1+"' and '"+years2+"-"+month2+"-"+day2+"'");    
               i=0;
            while(rs.next()){
                //  prenCli = rs.getString("Prénom");
                 id = rs.getString("num_paiem");
                nomact = rs.getString("nom_act");
                typeact = rs.getString("type_act");
                dureact = rs.getString("dure_act");
                datepaiem = rs.getString("date_paiem");
                montant = rs.getString("montant_payer");
        
                Object[] materiel = {id,nomact,typeact,dureact,datepaiem,montant};
                dt.addRow(materiel);
            }
            i=i+1;
            if(dt.getRowCount()==0){
                JOptionPane.showMessageDialog(null, " Aucun resultat trouver!");
                // AfficheDisp("");
            }else{
                i=0;
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de rechercher\n"+e);
        }
    }
            
     
    public void Affiche_RechercheTot_P(){
        i=0;
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

        int day2,month2,years2;
            years2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().YEAR);
            month2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().MONTH)+1;
            day2=tfdateRech2.getCalendar().get(tfdateRech2.getCalendar().DAY_OF_MONTH);
        try{    				
               Class.forName("com.mysql.jdbc.Driver");
               con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
               stm = (Statement) con.createStatement();
               rs=stm.executeQuery("select sum(MONTANT_PAYER) from paiement where DATE_PAIEM between '"+years1+"-"+month1+"-"+day1+"' and '"+years2+"-"+month2+"-"+day2+"'");    
               
                i++;
              while (rs.next()) {
                   tftotalP.setText(rs.getString("sum(MONTANT_PAYER)"));
            }
               
	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}
    }
   
    
    public void Affiche_Recherche1Tot_P(){
        i=0;
        int day1,month1,years1;
            years1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().YEAR);
            month1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().MONTH)+1;
            day1=tfdateRech1.getCalendar().get(tfdateRech1.getCalendar().DAY_OF_MONTH);

        try{    				
               Class.forName("com.mysql.jdbc.Driver");
                con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bdcaisse","root","");
                 stm = (Statement) con.createStatement();
               rs=stm.executeQuery("select sum(MONTANT_PAYER) from paiement where DATE_PAIEM = '"+years1+"-"+month1+"-"+day1+"'");    
               
                i++;
              while (rs.next()) {
                   tftotalP.setText(rs.getString("sum(MONTANT_PAYER)"));
            }

	}catch(Exception e){
           // JOptionPane.showMessageDialog(null,"Erreur\n"+e);
	}           
    
    }
    
  private void imprimer(){
   try{
        MessageFormat header=new MessageFormat("LISTE DES PAIEMENTS");
        MessageFormat footer =new MessageFormat("Page{0,number,integer}");
        tablepaiem.print(JTable.PrintMode.FIT_WIDTH,header,footer);
    }catch(Exception e){
       System.out.format("cannot print%s%n");
       e.getMessage();
    }
   }
}

